### ISSUE TITLE
Lagrangian observations datasets

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#10]
What list of datasets should we use as examples for the project?

- GulfDrifters: A consolidated surface drifter dataset for the Gulf of Mexico ([link](https://zenodo.org/record/4421585))
- Strateole-2: Long-duration balloon flights at the tropical tropopause ([link](https://strateole2.aeris-data.fr))
- WHOI gliders ([link](http://rtodd.whoi.edu/data.html))
- AOML gliders ([link](https://www.aoml.noaa.gov/data-products/))

**Comment by kevinsantana11** [comment]
The information presented here will be presented in the following project: https://github.com/orgs/Cloud-Drift/projects/3 for conciseness
