### ISSUE TITLE
Update README.m

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#106]
- [ ] Move first and center the link to the documentation
- [ ] move down the install section

What is now the recommended use of the `.yml` file? And as a corollary, the use of the `clouddrift` environment that can be created from it? I understand we removed this from the README some time ago.

**Comment by philippemiron** [comment]
The environment is there for two reasons:
1. It is used by the github actions (tests, and website) to download the dependencies and install the latest version of `clouddrift` from the github repo.
2. If someone (us) wants a simple environment to test `clouddrift` latest code.

**Comment by selipot** [comment]
> The environment is there for two reasons:
> 
> 1. It is used by the github actions (tests, and website) to download the dependencies and install the latest version of `clouddrift` from the github repo.

Great

> 2. If someone wants a simple environment to test `clouddrift` latest code.

Ok cool so should we add this back in the README? As an example? 

And right now I don't know what the test section is about? The automatic tests to make sure the whole library is consistent?

**Comment by philippemiron** [comment]
We could add it back. Yes, there are automatic tests (e.g. https://github.com/Cloud-Drift/clouddrift/blob/main/tests/analysis_tests.py) that gets executed after each modification to validate the code.
