### ISSUE TITLE
update gdp.py

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#107]
Updates to implement:

- [x] Right now the new individual hourly files are split into two folders on the FTP server. This causes the `adapter.gdp.to_raggedarray` to fail I think. I have asked @RickLumpkin to put them all in a single folder but could we pass `GDP_DATA_URL` potentially as a list of folders/url? Since it may be good idea to split GPS and Argos (or not)
- [x] since we are preparing `gdp6h.py` could we change the name `gdp.py` to `gdp1h.py`?
- [x] the `order_by_date` function should be updated: with the addition of the `start_date` we should sort as such and maybe be able to select another criteria such as `deploy_date` or `end_date`.

**Comment by philippemiron** [comment]
For step 1 it's not that simple with how the code is done. Because we have the option to construct by `drifter_ids [list]: list of drifters to retrieve (Default: all)`, you must know what drifters IDs are in what folders. I'm doing it in [gdp6h.py](https://github.com/Cloud-Drift/clouddrift-examples/blob/main/data/gdp6h.py):

```
# find out what drifters are part of each directory
dict_id = {}
all_drifter_ids = np.empty(0, dtype="int")
print("Listing AOML directory...")
for directory in aoml_directories:
    print(join(aoml_https_url, directory))
    urlpath = urllib.request.urlopen(join(aoml_https_url, directory))
    string = urlpath.read().decode("utf-8")
    pattern = re.compile("drifter_[0-9]*.nc")
    filelist = pattern.findall(string)
    folder_ids = np.unique([int(f.split("_")[-1][:-3]) for f in filelist])
    all_drifter_ids = np.append(all_drifter_ids, folder_ids)
    dict_id |= dict.fromkeys(folder_ids, directory)
```
so something like this would have to be added.

Then when you want to retrieve the files, I did the following:

```
for i in drifter_ids:
    file = f"drifter_{i}.nc"
    directory = dict_id[I]
    urls.append(join(aoml_https_url, directory, file))
    files.append(join(folder, directory, file))
```

For step 3, there is no `start_date` in the [directory file](https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/dirfl_1_5000.dat). Or maybe they put it in another folder? Currently, there are 3 dates: deployment, end, drogue loss, see the name of the columns [here](https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/header_dirfl.txt).

**Comment by selipot** [comment]
For step 1 let's hold on and see if version 2.01 is distributed eventually in a single directory as I requested. I have downloaded all the files, I could put them in a single directory, but there is no option for specifying a local folder where to get the data, correct? This `clouddrift.adapters.gdp.to_raggedarray` is only for generating the ragged array from the FTP server?

For step 3 the `start_date` is not in the deployment file but is a new variable in the individual netcdf files. Would this work?

**Comment by selipot** [comment]
Isn't the first date listed in `https://www.aoml.noaa.gov/phod/dac/dirall.html`?

**Comment by philippemiron** [comment]
> For step 1 let's hold on and see if version 2.01 is distributed eventually in a single directory as I requested. I have downloaded all the files, I could put them in a single directory, but there is no option for specifying a local folder where to get the data, correct? This `clouddrift.adapters.gdp.to_raggedarray` is only for generating the ragged array from the FTP server?

Not yet #94 ..

> For step 3 the `start_date` is not in the deployment file but is a new variable in the individual netcdf files. Would this work?

I would rather get the order by reading the directory file once than having to open all the files.

**Comment by philippemiron** [comment]
> `https://www.aoml.noaa.gov/phod/dac/dirall.html`

There is still only 3 dates there.. maybe they just didn't update the `header_drift.txt` file, https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/. If this is the case, then ordering by the `deployment_date` would be correct.
