### ISSUE TITLE
`segment` function

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#113]
Let's discuss the `segment` function here, inspired by jLab's [cellsplit](https://github.com/jonathanlilly/jLab/blob/master/jCell/cellsplit.m).

Suggested interface:

```python
def segment(
    array: np.ndarray,
    tolerance: float | timedelta
) -> list[np.ndarray]:
    """Segment an array into segments that do not contain gaps
    longer than the value of tolerance.
    """
```

@selipot you mentioned [here](https://github.com/Cloud-Drift/clouddrift/pull/112#issuecomment-1432111712) that we would use `segment` for arbitrary criteria. How do you envision the interface look like? What are some other possible gaps other than time?

**Comment by selipot** [comment]
As an example the GDP hourly dataset contains a variable called 'gap' which is the temporal gap between between the two closest observations used for the estimation. Another conceptual idea is depth difference for 3d trajectory or any other tracer along s trajectory we may not think of. Let's be open and the most general possible.

**Comment by milancurcic** [comment]
OK, so what does this look like in an API? It seems to me that in addition to the array to segment, we need to pass the coordinate data along which we're segmenting, and the axis, if the array is multidimensional. How does this look like:

```python
def segment(
    array: np.ndarray,
    coord_data: np.ndarray,
    tolerance: float | timedelta,
    axis: int = -1
) -> list[np.ndarray]:
    """Segment an array into segments that do not contain gaps
    longer than the value of tolerance along coord_data.
    The segmenting of multidimensional arrays is done along the specified
    axis, which defaults to -1 (fastest-varying).
    """
```

**Comment by selipot** [comment]
Here as arguments you pass the array to segment, the coordinate along which to segment, and tolerance. Passing along the axis I think makes sense. But is returning a list of arrays the most efficient way to do this? Segmenting essentially creates a new rowsize variable. So the segmentation should be aware of the existing rowsize and return a new rowsize (or a new set of ids which sounds difficult or flawed):
```
def segment(
    array: np.ndarray,
    rowsize,
    coord_data: np.ndarray,
    tolerance: float | timedelta,
) -> newrowsize:
    "splits ragged arrays (trajectories) into segments that do not contain gaps larger 
    than the value of tolerance along coord_data.
    The segmenting of multidimensional arrays is done along the specified
    axis which must match the length of coord_data.
```

**Comment by selipot** [comment]
> Ah, I misunderstood what this function should return. Yes, simply returning the new row size is simpler and lets the user decide how best to use it. In that case, we also don't need to pass `array`, but only `coord_data` (which we can then call just `array`).

True

> Do we need to pass in the `rowsize` as input? I think `rowsize` is here as input because you want to segment a ragged array (akin to jLab's `cellsplit`). In this case, the result would be a list of row-size arrays, because the user needs to know which segmentation was due to a change in trajectory, and which is due to a gap in data. Do you agree?

Completely

> However, if we define this function to operate on a single trajectory (that may have gaps), then we don't need to pass `rowsize`, and the result can be just the new row-size array for that trajectory. And running `segment` on a ragged array would be relatively straightforward considering that now we have `unpack_ragged`, e.g.:
> 
> ```python
> segments = [segment(time, tolerance=3600) for time in unpack_ragged(ds.time.values, ds.rowsize)]
> ```
> 
> And if we define `segment` to work on ragged arrays, then it would be:
> 
> ```python
> segments = segment(ds.time, ds.rowsize, tolerance=3600)
> ```
> 
> We could make it work both ways if we make `rowsize` to be an optional argument:
> 
> ```python
> def segment(
>     array: np.ndarray,
>     tolerance: float | timedelta,
>     rowsize: np.ndarray = None,
>     axis: int = -1
> ) -> newrowsize: np.ndarray | list[np.ndarray]
> ```
> 
> With this definition, both of these should work:
> 
> ```python
> segments = [segment(time, tolerance=3600) for time in unpack_ragged(ds.time.values, ds.rowsize)]
> segments = segment(ds.time, tolerance=3600, rowsize=ds.rowsize)
> ```

Great!

> (and in a separate PR, we could apply the same "rowsize-optional" approach to `velocity_from_position` and other future functions.)

Even greater!

Another example of the use of `segment` would be to actually define `rowsize` in the first place by using an array of ids as the first argument. A jump of one or more indicates the separation between trajectories if we decide that the split occur for (absolute?) difference values (better than gap even if gap is absolute) as large or larger than the tolerance.

**Comment by selipot** [comment]
Maybe we need an option for the tolerance to be positive or negative?

**Comment by milancurcic** [comment]
What do you think about this approach? The tolerance can be either positive or negative. If both positive and negative tolerance is needed, i.e. segment if the change is, for example, < -2 and > 4, then I'd just recommend the user to segment twice, first for a positive tolerance and one more time for the negative. An element-wise union of the two results should yield the correct result.

**Comment by selipot** [comment]
That could work. Not sure what *element-wise union* means here. The first pass would provide a `rowsize1` which would then need to be passed as an argument to produce `rowsize2` with the second pass. Is that a union? 

Deriving the rowsize variable from ids would then take 2 steps because IDs may not be sorted. I think that is ok for the users as long as we explicitly provide such an example
