### ISSUE TITLE
Question about `recast_longitude` implementation

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#121]
@philippemiron, I noticed that in `rot` you cast to to complex-phase:

```python
def rot(x: np.ndarray) -> np.ndarray:
    x = np.mod(x + np.pi, 2 * np.pi) - np.pi  # convert to [-pi, pi]
    return np.exp(1j * x)
```

and in `recast_longitude` you use `np.angle`:

```python
    return (
        np.mod(
            np.divide(360, 2 * np.pi)
            * np.unwrap(np.angle(rot(np.divide(2 * np.pi, 360) * (lon - lon0)))),
            360,
        )
        + lon0
    )
```

If `rot` is instead defined as 

```python
def rot(x: np.ndarray) -> np.ndarray:
    return np.mod(x + np.pi, 2 * np.pi) - np.pi  # convert to [-pi, pi]
```

could the `recast_longitude` implementation not be simpler:

```python
    return (
        np.mod(
            np.divide(180, np.pi)
            * np.unwrap(rot(np.deg2rad(lon - lon0))),
            360,
        )
        + lon0
    )
```

Notice the `np.deg2rad`, `np.angle`, and simplified `np.divide`.

It seems to me that it does the same thing without the real-to-complex round-trip, but it's possible that you did what you did for a good reason that I don't see.

**Comment by milancurcic** [comment]
I just tried it and the tests continue to pass. Here's the diff

```diff
diff --git a/clouddrift/sphere.py b/clouddrift/sphere.py
index 186ccc2..2779b25 100644
--- a/clouddrift/sphere.py
+++ b/clouddrift/sphere.py
@@ -25,8 +25,7 @@ def rot(x: np.ndarray) -> np.ndarray:
         rot(np.pi) # approx. (-1+0j)
         rot(3 * np.pi / 2) # approx. (0-1j)
     """
-    x = np.mod(x + np.pi, 2 * np.pi) - np.pi  # convert to [-pi, pi]
-    return np.exp(1j * x)
+    return np.mod(x + np.pi, 2 * np.pi) - np.pi  # convert to [-pi, pi]
 
 
 def recast_longitude(lon: np.ndarray, lon0: Optional[float] = -180) -> np.ndarray:
@@ -77,8 +76,8 @@ def recast_longitude(lon: np.ndarray, lon0: Optional[float] = -180) -> np.ndarra
 
     return (
         np.mod(
-            np.divide(360, 2 * np.pi)
-            * np.unwrap(np.angle(rot(np.divide(2 * np.pi, 360) * (lon - lon0)))),
+            np.divide(180, np.pi)
+            * np.unwrap(rot(np.deg2rad(lon - lon0))),
             360,
         )
         + lon0
```

**Comment by philippemiron** [comment]
I did that following https://github.com/Cloud-Drift/clouddrift/issues/63#issuecomment-1367428773. If it does the same, we should modify it. Then I guess to `rot` function should also be renamed.

**Comment by milancurcic** [comment]
How should `rot` be called if it gets updated to return the angle instead of the complex components? It still rotates the input. I don't know what's the correct terminology for this.

**Comment by selipot** [comment]
I am not sure why the rot function does here what it does. It differs from the jlab function which simply does
```
def rot(x: np.ndarray) -> np.ndarray:
    return np.exp(1j * x)
```

**Comment by philippemiron** [comment]
[Here](https://github.com/jonathanlilly/jLab/blob/master/jCommon/rot.m) it does nodify the angle by doing this `x=rot_mainangle(x)` no?

**Comment by philippemiron** [comment]
I guess like in jlab, `rot_mainangle()` could be a possible good name for the function.

**Comment by philippemiron** [comment]
I'm probably missing something, but this is passing all the tests:

```
return np.mod(lon - lon0, 360) + lon0
```

**Comment by selipot** [comment]
> [Here](https://github.com/jonathanlilly/jLab/blob/master/jCommon/rot.m) it does modify the angle by doing this `x=rot_mainangle(x)` no?

it modifies it by returning modulus from 2pi but does not rotate or anything.

**Comment by selipot** [comment]
> I'm probably missing something, but this is passing all the tests:
> 
> ```
> return np.mod(lon - lon0, 360) + lon0
> ```

I agree this seem to work. I feel that for user convenience there should be convenience wrapper functions (is that how you call it?) for the cases lon0 = 0 and lon0= -180. Or should it suffice to provide these cases in the examples of the docstring?

```
def recast_longitude(lon,lon0):
    return np.mod(lon - lon0, 360) + lon0
def recast180(lon):
    return recast_longitude(lon,-180)
def recast360(lon):
    return recast_longitude(lon,0)
```

Why doesn't the docstring have examples already?

**Comment by philippemiron** [comment]
Yeah, I think it can be useful to have this function, even if very simple. 

The code already has the examples, see [here](https://github.com/Cloud-Drift/clouddrift/blob/main/clouddrift/sphere.py). I also added with `lon0=20` -> longitude values are converted to range `[20, 380]`, which can be useful to avoid cutting the major ocean basins.

**Comment by philippemiron** [comment]
I pushed this #124.
