### ISSUE TITLE
Should clouddrift adopt a shorthand `cd`?

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#122]
```python
import numpy as np
import xarray as xr
import clouddrift as cd
```

Through examples, we could guide the user on how to use clouddrift. One thing that we could show/recommend is to import the `clouddrift` as `cd`, like `np`, `xr`, or `pd`.

Has `cd` been claimed by any library? I'm not aware of it.

One advantage of this style is to provide a single, short import for `clouddrift` and a 2-letter namespace for users to not have to explicitly import stuff by name.

**Comment by selipot** [comment]
I like `cd` but isn't it interpreted by default as "change directory" by python? If you `import clouddrift as cd`, don't you loose the `cd` command? 

We could `import clouddrift as dr`?

**Comment by milancurcic** [comment]
Good question. I never tried `cd` in Python before so I just did. It looks like it's not a Python built-in, but an IPython extension:

```
(venv) milan@hyperion:~/Work/clouddrift/clouddrift$ python
Python 3.9.5 (default, Nov 23 2021, 15:27:38) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> cd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cd' is not defined
>>> 
(venv) milan@hyperion:~/Work/clouddrift/clouddrift$ ipython
Python 3.9.5 (default, Nov 23 2021, 15:27:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: cd
/home/milan

In [2]: 
```

And even if it was, Python doesn't allow you to override built-in stuff like Fortran does.

**Comment by selipot** [comment]
<img width="830" alt="Screenshot 2023-02-21 at 7 35 23 AM" src="https://user-images.githubusercontent.com/7576346/220346465-f20952a0-f958-451a-a9c9-647a17fd4cfc.png">

**Comment by selipot** [comment]
```
(clouddrift) selipot@liverbird:clouddrift $ ipython
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:24:27) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: pwd
Out[1]: '/Users/selipot/projects.git/clouddrift'

In [2]: cd tests
/Users/selipot/projects.git/clouddrift/tests

In [3]: import clouddrift as cd

In [4]: cd ..
  Cell In[4], line 1
    cd ..
        ^
SyntaxError: invalid syntax


In [5]: cd?
Type:        module
String form: <module 'clouddrift' from '/Users/selipot/opt/miniconda3/envs/clouddrift/lib/python3.10/site-packages/clouddrift/__init__.py'>
File:        ~/opt/miniconda3/envs/clouddrift/lib/python3.10/site-packages/clouddrift/__init__.py
Docstring:   <no docstring>

In [6]: 

```

**Comment by milancurcic** [comment]
Looks good :+1:

**Comment by selipot** [comment]
Good? cd is a conflict in my typical environment.

**Comment by milancurcic** [comment]
By good, I meant your output looks as I expected it to look.

It's a valid argument against doing this if you want to keep IPython's `cd` (you can still do `%cd ..`).

**Comment by selipot** [comment]
So let's plan on using `import clouddrift as dr`?

**Comment by milancurcic** [comment]
Personally, I don't find it recognizable enough. I think longer shorthands become more recognizable, like `cdr` or `cldr`, but they have the obvious downsides. I'll keep thinking about this, but for the time being my preferences are:

1. `cd`
2. No shorthand
3. `cdr`
4. `cldr`
5. `dr`

**Comment by selipot** [comment]
1. definitively a no for me.
2. Not a good option as `clouddrift` is too long
3. 😑
4. my favorite
5. 😑

Thank you for bringing this issue!

**Comment by milancurcic** [comment]
@philippemiron What do you think about `cldr` or `dr`?

**Comment by philippemiron** [comment]
I guess `cldr`, but I'm good either way.

**Comment by philippemiron** [comment]
Actually I would vote either `dr` or `cl`, 4 letters is too long.

**Comment by selipot** [comment]
It should start with `c` and the second letter should ideally recall an accent in the name which is why `cd` would have been perfect but no way since it corresponds to change directory. `cl` is acceptable to me.

**Comment by milancurcic** [comment]
@selipot can you reconsider your use of `cd`? It's not a Python thing, and in IPython you could use `%cd`. Ultimately it's your call. I think it would be a shame to pass on `cd` which I agree is the perfect name. I also think `cl` is acceptable and my second choice. I did a very brief search and found no major packages that alias as `cl`.

**Comment by selipot** [comment]
I am not convinced! We have no other users to ask unfortunatelly

**Comment by selipot** [comment]
Ok, can we close this? I think `cd` as a shorthand is doable.

**Comment by milancurcic** [comment]
Let's keep it open just until we promote it in a prominent place, for example when I update this page:

https://cloud-drift.github.io/clouddrift/usage.html
