### ISSUE TITLE
Weird bar covering the navbar in the docs website

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#125]
Can you please take a look at https://cloud-drift.github.io/clouddrift and let me know if you see this bar at the top that says "Skip to main content":

![Screenshot from 2023-02-23 14-09-24](https://user-images.githubusercontent.com/4133310/221006417-8c585a5c-2e89-43b4-8c32-c0110bc80ce9.png)

What is that? I don't recall it being there, and I don't think it should be. Even stranger, it appears on the NumPy docs too:

https://numpydoc.readthedocs.io/en/latest/

I wonder if it's a Sphinx or theme bug.

**Comment by selipot** [comment]
I am not seeing it on any of three browsers (Safari, Chrome, Firefox)

**Comment by milancurcic** [comment]
Good to know. I also don't have the issue on my laptop, only on my office desktop. Could be an outdated browser thing. Will close.
