### ISSUE TITLE
Discussion ragged array support

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#127]
I just saw that the segment function supports ragged array, and I was wondering what you think of including something like this inside `clouddrift`.

```python
def apply_ragged(func, arr, rowsize, *args, **kwargs):
    """
    Apply a function over segments of a ragged array
    """
    if not sum(rowsize) == len(x):
            raise ValueError("The sum of rowsize must equal the length of x.")
            
    output = []
    start = 0
    for r in rowsize:
        end = start + int(r)
        output.append(func(arr[start:end], *args, **kwargs))
        start = end
    return np.concatenate(output)

from concurrent import futures
def apply_ragged_thread(func, arr, rowsize, *args, **kwargs):
    """
    Apply a function over segments of a ragged array
    """
    if not sum(rowsize) == len(x):
            raise ValueError("The sum of rowsize must equal the length of x.")
    
    def wrapper(x):
        return func(x, *args, **kwargs)        
        
    with futures.ThreadPoolExecutor() as executor:
        outputs = executor.map(wrapper, np.array_split(arr, np.cumsum(rowsize[:-1])))
    return np.concatenate([o for o in outputs])
```

The main advantage is that we can remove `if rowsize is None:` in `segments` (and future functions that I guess would require a similar construct), but of course the user now has to use this function if they have a ragged array. 

For example, I've tested with the `segment` function.

```python
x = [0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4]
rowsize = [3, 2, 6]
segment(x, 0.5, rowsize)
> array([1, 2, 1, 1, 1, 4, 1])
```

```python
apply_ragged(segment, x, rowsize, tolerance=0.5)
> array([1, 2, 1, 1, 1, 4, 1])
```

```python
apply_ragged_thread(segment, x, rowsize, tolerance=0.5)
> array([1, 2, 1, 1, 1, 4, 1])
```

PS: So far, I have not found an elegant way of performing the same for `n` ragged array arguments, e.g. `velocity_from_position`, which expects `x`, `y`, and `t`.

**Comment by philippemiron** [comment]
Ok, I'm pretty happy because I just now managed to make it work right now for `n` parameters and arguments.

Here are the new functions. There are two versions, one is a simple map and the other one is doing the calculation on different threads. But basically both are doing the same thing.

```
from concurrent import futures
from collections.abc import Iterable
import numpy as np
from clouddrift.analysis import segment, velocity_from_position

def apply_ragged(func, rowsize, arrs, *args, **kwargs):
    """
    Apply a function over segments of a ragged array
    """
    if not isinstance(arrs[0], Iterable):
        arrs = [arrs]
    
    for arr in arrs:
        if not sum(rowsize) == len(arr):
            raise ValueError("The sum of rowsize must equal the length of arr.")
    
    def wrapper(iterargs):
        return func(*iterargs, **kwargs)
    
    arrs = [np.array_split(arr, np.cumsum(rowsize[:-1])) for arr in arrs]
    iterargs = [[arrs[i][j] for i in range(len(arrs))] for j in range(len(arrs[0]))]
      
    # combine other arguments
    for arg in iterargs:
        if args: arg.append(*args)
    
    results = list(map(wrapper, iterargs))
    
    # concatenate the n outputs arguments
    if isinstance(results[0], tuple):
        outputs = []
        for i in range(len(results[0])):
            outputs.append(np.concatenate([r[i] for r in results]))
        return tuple(outputs)
    else:
        return np.concatenate([r for r in results])
    
    
def apply_ragged_thread(func, rowsize, arrs, *args, **kwargs):
    """
    Apply a function over segments of a ragged array
    """
    if not isinstance(arrs[0], Iterable):
        arrs = [arrs]
    
    for arr in arrs:
        if not sum(rowsize) == len(arr):
            raise ValueError("The sum of rowsize must equal the length of arr.")
    
    def wrapper(iterargs):
        return func(*iterargs, **kwargs)
    
    arrs = [np.array_split(arr, np.cumsum(rowsize[:-1])) for arr in arrs]
    iterargs = [[arrs[i][j] for i in range(len(arrs))] for j in range(len(arrs[0]))]
      
    # combine other arguments
    for arg in iterargs:
        if args: arg.append(*args)
    
    with futures.ThreadPoolExecutor(max_workers=1) as executor:
        results = executor.map(wrapper, iterargs)
    
    # concatenate the n outputs arguments
    results = list(results)
    if isinstance(results[0], tuple):
        outputs = []
        for i in range(len(results[0])):
            outputs.append(np.concatenate([r[i] for r in results]))
        
        return tuple(outputs)
    else:
        return np.concatenate([r for r in results])
```

I was testing with those 3 functions:

```
def test(x, tolerance):
    return x + tolerance

def test2(x, y, tolerance):
    return x + y + tolerance

def test3(x, y, z, tolerance):
    return x + y + z + tolerance
```

And you can see the tests below.

```
# data
rowsize = [3, 3, 3]
x = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
y = 2*x
z = 3*x
tolerance = 0.5

# one arguments
a = apply_ragged(test, rowsize, x, tolerance)
b = apply_ragged(test, rowsize, x, tolerance=tolerance)
c = apply_ragged_thread(test, rowsize, x, tolerance)
d = apply_ragged_thread(test, rowsize, x, tolerance=tolerance)

np.testing.assert_allclose(a, b)
np.testing.assert_allclose(a, c)
np.testing.assert_allclose(a, d)
np.testing.assert_allclose(a, x + tolerance)

# two arguments
a = apply_ragged(test2, rowsize, [x, y], tolerance)
b = apply_ragged(test2, rowsize, [x, y], tolerance=tolerance)
c = apply_ragged_thread(test2, rowsize, [x, y], tolerance)
d = apply_ragged_thread(test2, rowsize, [x, y], tolerance=tolerance)

np.testing.assert_allclose(a, b)
np.testing.assert_allclose(a, c)
np.testing.assert_allclose(a, d)
np.testing.assert_allclose(a, x + y + tolerance)

# three arguments
a = apply_ragged(test3, rowsize, [x, y, z], tolerance)
b = apply_ragged(test3, rowsize, [x, y, z], tolerance=tolerance)
c = apply_ragged_thread(test3, rowsize, [x, y, z], tolerance)
d = apply_ragged_thread(test3, rowsize, [x, y, z], tolerance=tolerance)

np.testing.assert_allclose(a, b)
np.testing.assert_allclose(a, c)
np.testing.assert_allclose(a, d)
np.testing.assert_allclose(a, x + y + z + tolerance)
```

And finally, for a functions that returns multiple values, like `velocity_from_position`.

```
rowsize = [2, 3, 4]
x = np.array([1, 2, 1, 3, 5, 1, 5, 8, 11])
y = np.zeros_like(x)
t = np.array([1, 2, 1, 2, 3, 1, 2, 3, 4])
velocity_from_position(x, y, t, coord_system="cartesian")
> (array([1., 1., 2., 2., 2., 4., 3., 3., 3.]),
 array([ 0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.]))
```

This is the result when using the ragged arrays as a simple 1d array (calling the function directly).

```
rowsize = [2, 3, 4]
x = np.array([1, 2, 1, 4, 6, 1, 5, 8, 11])
y = np.zeros_like(x)
t = np.array([1, 2, 1, 2, 3, 1, 2, 3, 4])
u1, v1 = apply_ragged(velocity_from_position, rowsize, [x, y, t], coord_system="cartesian")
u2, v2 = apply_ragged_thread(velocity_from_position, rowsize, [x, y, t], coord_system="cartesian")

np.testing.assert_allclose(u1, u2)
np.testing.assert_allclose(v1, v2)

u1, v1
> (array([1., 1., 3., 2., 2., 4., 3., 3., 3.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0.]))
```

**Comment by selipot** [comment]
Looks super interesting! Let's discuss. I am trying to think of the implications. 

Oh I did not know about the `concurrent.futures` module. Is that a straightforward thing to use to conduct parallel tasks with python?

**Comment by philippemiron** [comment]
Yes, it's one of the options.

**Comment by selipot** [comment]
So it comes down to the API being
1) `apply_ragged(func,x,rowsize,...)` or 
2) `func(x,rowsize,...)`

Option 1 is easier for the developers for sure. Not sure what's easier for a simple user? I guess applying something like `velocity_from_position` without the need to explicitly write a loop? I like it.

**Comment by philippemiron** [comment]
True,  both then 2 assumes that all the clouddrift function will have `if rowsize: do` this, `else: do` that, which is the case in `segments`, but not in `velocity_from_position` right now.

**Comment by milancurcic** [comment]
I think this would be a very nice addition and a good strategy for going forward.

From the user's perspective, the two APIs seem similar to me in the sense that with either of the two strategies, the user has to learn how it works and use it consistently. 1 does seem a tad more advanced since it's a functional approach, and it may seem complicated to an imperative Python user. And with 2, the user has to remember to pass `rowsize` to a function if it's to work with ragged arrays.

From a developer's perspective, 1 is obviously better and easier to maintain.

Overall, and pending more in-depth review, I'm in favor for 1. @philippemiron since you already have a working implementation, can you start a PR and we can play with it and improve if needed?

Can this approach be generalized to work with N-d arrays? (I'm not necessarily advocating for that, merely wondering).

**Comment by milancurcic** [comment]
> True, both then 2 assumes that all the clouddrift functions will have if rowsize: do this, else: do that, which is the case in segments, but not in velocity_from_position right now.

Indeed. So far we have discussed and agreed on wanting functions to support both contiguous 1-d arrays and ragged arrays, but we have not quite yet specified a uniform and consistent strategy on how exactly to do it. I think this issue (and its future PR) may do exactly that--provide a consistent framework for functions to apply to both contiguous and ragged arrays.

**Comment by philippemiron** [comment]
I can try to implement this in a PR. I have not tested n dimensions of ragged arrays, and to be honest I'm also not sure how this would apply in our case.

**Comment by selipot** [comment]
A good test of performance would be to input the GDP ragged array version 2 and use `velocity_from_position` on the `lat` and `lon` arrays.

**Comment by milancurcic** [comment]
Is it feasible to use `ProcessPoolExecutor` instead of `ThreadPoolExecutor` here? From my limited understanding, the former is more optimal for CPU-bound work. But it does have a limitation on what kind of data can be returned.

**Comment by philippemiron** [comment]
I guess it's feasible, but I'm not exactly sure how. Problem is, `ProcessPoolExecutor` uses `pickle` to transfer memory across processes, and the `lambda` function can't be pickled. I remember seeing that there is a way to make this work by defining a wrapper function (similarly to what I had on top of this message) but it must be defined outside of the scope of the function. Like this (from [here](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function)).

```
from multiprocessing import Pool

class Test:
    def __init__(self, x):
        self.x = x
    
    @staticmethod
    def test(x):
        return x**2


    def test_apply(self, list_):
        global r
        def r(x):
            return Test.test(x + self.x)

        with Pool() as p:
            l = p.map(r, list_)

        return l



if __name__ == '__main__':
    o = Test(2)
    print(o.test_apply(range(10)))
```


I have not figured out how to generate and pass the arguments properly in that case...
