### ISSUE TITLE
Sort GDP by start date instead of deployment date

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#136]

**Comment by milancurcic** [comment]
dirfl_*.dat that we currently use have deployment date but not start date.

https://www.aoml.noaa.gov/phod/dac/dirall.html has start date, but doesn't have the IDs that we need.

Although start date would be preferred, @selipot and I decided to for now stick with deployment date.

**Comment by selipot** [comment]
Correction, it seems that the dirfl_*.dat files have the start dates (🤯)

**Comment by milancurcic** [comment]
Hmm. Did we mislabel it in the code that reads dirfl_*.dat files?

**Comment by selipot** [comment]
Probably because the `header_dirfl.txt` file on the FTP used to state that these were the deployment dates and time whereas our latest email correspondence and latest correction of that file now seem to indicate that they are the start date and times.

**Comment by selipot** [comment]
Am trying to get final confirmation from Shaun Dolk (I thought he was on github) and @RickLumpkin .

**Comment by milancurcic** [comment]
OK it sounds like what we (i.e. in clouddrift.adapters.gdp) call "Deployment Date" is really "Start Date" as in date of first QC data point. If that's correct, then we merely need to fix our label in the code, but we will continue sorting using this date value.

**Comment by selipot** [comment]
yes, yes, and yes.
