### ISSUE TITLE
Sort out the data-metadata mismatch for hourly GDP

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#141]
While the experimental feed of GDP was worked out in #111, there are inconsistencies in the "production" feed of GDP hourly. @philippemiron reports:

I tried tonight to generate the ragged array and there are still errors with the files. Here is a summary of what I’ve so you don’t have to redo the same thing.

```python
import os
import xarray as xr
import pandas as pd
import numpy as np
from clouddrift.adapters.gdp import to_raggedarray, GDP_DATA_URL, GDP_DATA_URL_EXPERIMENTAL

ra = to_raggedarray(n_random_id=100)

> Downloading files: 100%|███████████████████| 100/100 [00:00<00:00, 88580.87it/s]
  Retrieving the number of obs: 100%|█████████████| 98/98 [00:04<00:00, 24.26it/s]
  Filling the Ragged Array: 100%|█████████████████| 98/98 [00:05<00:00, 17.43it/s]
```

As you can see, there are 100 drifters selected. And then, 98 in the ragged arrays.
100 files are downloaded, so the code that look at this website (https://www.aoml.noaa.gov/ftp/pub/phod/lumpkin/hourly/v2.00/netcdf/) page and extract the IDs is working fine.
If I do the following:

```python
# with the same seed we get the same drifters as above
rng = np.random.RandomState(42)
selected_ids = sorted(rng.choice(drifter_ids, 100, replace=False))

# read the directory files
df = get_gdp_metadata()

# look how many IDs are in the directory files
np.sum(np.in1d(selected_ids, df.ID))
> 98
```

Then with this:

```python
selected_ids[~np.in1d(selected_ids, df.ID)]
> array([ 2022710, 12469250])
```

Those are the two IDs (in my list of 100 drifters) that are not in the metadata. But you can look on the page above that they are files with those IDs.
And, while investigating that, I also looked at the IDs inside the downloaded files. Technically, I would expect them to match with the filenames pattern (e.g. drifter_{i}.nc should have an ID = {i}).

```python
file_ids = []
for i in selected_ids:
    f = os.path.join(GDP_TMP_PATH, f"drifter_{i}.nc")
    file_ids.append(int(xr.open_dataset(f, decode_times=False).ID.values))
file_ids = np.array(file_ids)

selected_ids[~np.in1d(selected_ids, file_ids)]
> array([300234060940960, 300234060942970, 300234060955910, 300234061669330,
       300234063251240, 300234063714570, 300234063801140, 300234063894730,
       300234064011120, 300234064766670, 300234064827500, 300234064828550,
       300234065256040, 300234065510570, 300234065510710, 300234065804070,
       300234066210830, 300234066308040, 300234066310150, 300234066314860,
       300234066513300, 300234066537040, 300234067545070, 300234067772920,
       300234068246720])
```

So for 25 files, the ID inside the NetCDF do not match the filename pattern. For example, if we take the first one of this list:

```python
i = 300234060940960
xr.open_dataset(os.path.join(GDP_TMP_PATH, f"drifter_{i}.nc"), decode_times=False).ID.values
> array([b'60940960'], dtype='|S10')
```

**Comment by milancurcic** [comment]
@RickLumpkin, the non-experimental GDP feed (https://www.aoml.noaa.gov/ftp/pub/phod/lumpkin/hourly/v2.00/netcdf/) has 17324 files. Of those, 45 are not in the directory files:

```python
In [17]: np.setdiff1d(drifter_ids, gdp_metadata.ID.values)
Out[17]: 
array([        2020620,         2020710,         2021710,         2022690,
               2022710,         2023710,         2024660,         2024710,
               2025710,         2026650,         2026710,         2027650,
               2027690,         2027700,         2028610,         2028650,
               2028700,         2029610,         2029700,         2516470,
               2520260,         2520280,         2521250,         2521260,
               2522250,         2522260,         2523250,         2523260,
               2524160,         2524250,         2525260,         2527250,
               2527260,         2528250,         2528260,         2529260,
               2624430,         2720390,         2720460,         2726390,
              12294040,        12469250,        60725400, 300534061493010,
       300534061493020])
```

**Comment by selipot** [comment]
This is a new behavior and is not good. We used to be able to create the ragged array for the current version (2.00) with the 17324 drifters. The directory files have changed, that the only thing I can think of.

**Comment by philippemiron** [comment]
Ping on this. Does anyone have an idea of when this will be fixed?

**Comment by selipot** [comment]
@milancurcic  Let's continue to investigate this with the DAC and @RickLumpkin

**Comment by selipot** [comment]
See email chain with @RickLumpkin : the 45 drifters listed above are found in the directory files with their 15-digit IDs. But note that they are not found in the online [dirall.html](https://www.aoml.noaa.gov/phod/dac/dirall.html).

```
    '300034012294040'
    '300034012469250'
    '300234060725400'
    '300034012020620'
    '300034012020710'
    '300034012021710'
    '300034012022690'
    '300034012022710'
    '300034012023710'
    '300034012024660'
    '300034012024710'
    '300034012025710'
    '300034012026650'
    '300034012026710'
    '300034012027650'
    '300034012027690'
    '300034012027700'
    '300034012028610'
    '300034012028650'
    '300034012028700'
    '300034012029610'
    '300034012029700'
    '300034012516470'
    '300034012520260'
    '300034012520280'
    '300034012521250'
    '300034012521260'
    '300034012522250'
    '300034012522260'
    '300034012523250'
    '300034012523260'
    '300034012524160'
    '300034012524250'
    '300034012525260'
    '300034012527250'
    '300034012527260'
    '300034012528250'
    '300034012528260'
    '300034012529260'
    '300034012624430'
    '300034012720390'
    '300034012720460'
    '300034012726390'
```

**Comment by RickLumpkin** [comment]
Hi all - quick reminder that that online version has the truncated IDs for
security reasons.  If you want the full IDs, use the dirfl files in
https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/

**Comment by selipot** [comment]
> Hi all - quick reminder that that online version has the truncated IDs for security reasons. If you want the full IDs, use the dirfl files in https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/
> […](#)

Thanks @RickLumpkin I had forgotten that!

**Comment by philippemiron** [comment]
I think this is done right?

**Comment by RickLumpkin** [comment]
Yes, this was done.  All IDs should be found in the directory file (the 15-digit version).
