### ISSUE TITLE
implement a function `ragged_to_2darray` and vice versa `2darray_to_ragged`

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#152]
ragged_to_2darray would fill gaps with FillValues
2darray_to_ragged would remove FillValues and define the rowsize variable

**Comment by philippemiron** [comment]
The step to do 2d to ragged is done in the numerical example [here](https://github.com/Cloud-Drift/clouddrift-examples/blob/main/notebooks/simulation-data.ipynb).

Basically you remove the nan, reshape, and if you store in dictionaries you can use the dataformat class to create the ragged array.
