### ISSUE TITLE
uv2latlon: integrates horizontal velocity to give latitude and longitude. See jLab function of the same name

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#153]
to be called `position_from_velocity`

**Comment by milancurcic** [comment]
@selipot should this be landmask-aware, perhaps as an option?

**Comment by selipot** [comment]
Could be as an option but remember that it could apply to atmospheric data and or non-Earth oceans :)

**Comment by philippemiron** [comment]
or 🐦 trajectories ;)
