### ISSUE TITLE
Prune ragged array by length

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#157]
As suggested by @philippemiron, pruning by length via `subset` works pretty well. I just tested it.

```python
In [29]: ds.rowsize
Out[29]: 
<xarray.DataArray 'rowsize' (traj: 98)>
array([ 5766, 19132, 17906,    86,  1540,  5738,  6631, 26063,  9806,
         786, 17715, 29482, 21391,  2506,  1685,  2142, 23807, 20817,
       15072, 43004,  3948, 11455, 10485,  8847, 18861,  8837,  7058,
         121,  3099,  2384,  8838,  4942,  6642,   306,  4217, 20184,
       34649,  4610, 11369, 10275,  4618,  7231,   281,  7644,  4510,
        1744,  1095,  1970,  4348,  7457,  4316, 12655, 11161,  5519,
        6107,  9643,  5535, 36824, 21370,  4602,  6458,  1193,  3129,
       16519, 10237,  5439,  3704, 11368,  4316,  5567, 11324,  8484,
        5983, 27429,   400,  4858,   562, 17205, 37007,  6513,  9416,
       23431, 19927,  6140,  9207,  1065, 13394,  9158,  5450,  1481,
         930,  5309,  5195,  6161,  3592,  2836,  1843,   221],
      dtype=int32)
Dimensions without coordinates: traj
Attributes:
    long_name:         Number of observations per trajectory
    sample_dimension:  obs
    units:             -

In [30]: subset(ds, criteria={"rowsize": (0, 1000)}).rowsize
Out[30]: 
<xarray.DataArray 'rowsize' (traj: 9)>
array([ 86, 786, 121, 306, 281, 400, 562, 930, 221], dtype=int32)
Dimensions without coordinates: traj
Attributes:
    long_name:         Number of observations per trajectory
    sample_dimension:  obs
    units:             -
```

I don't think a separate function is necessary, unless there is some extra functionality needed.

What do you think @selipot?

**Comment by selipot** [comment]
I think we should have another function that does not rely on the ragged array structure but just the passing of a rowsize argument, such as
```
>>> x,newrowsize = prune([1, 2, 3, 1, 2, 1, 2, 3, 4,],rowsize=[3, 2, 4],min=3) 
x = [1,2,3,1,2,3,4]
newrowsize = [3,3]
```

**Comment by philippemiron** [comment]
We can implement this, it probably takes more time to write the docstring than the function itself.

I'm thinking that we could separate the functions into two categories. 
1. can be applied to the complete datasets (to maintain the coordinates, metadata, etc.)
2. If it does not make sense, then we can create functions that returns _simple_ array.

PS: This almost does it too.. 
```
apply_ragged(lambda x, min_len: x if len(x) >= min_len else np.array([]), np.array([1, 2, 3, 1, 2, 1, 2, 3, 4]), rowsize=[3, 2, 4], min_len=3)

>  array([1., 2., 3., 1., 2., 3., 4.])
```

**Comment by philippemiron** [comment]
> I think we should have another function that does not rely on the ragged array structure but just the passing of a rowsize argument, such as
> 
> ```
> >>> x,newrowsize = prune([1, 2, 3, 1, 2, 1, 2, 3, 4,],rowsize=[3, 2, 4],min=3) 
> x = [1,2,3,1,2,3,4]
> newrowsize = [3,3]
> ```

ps: I guess this should be `newrowsize = [3, 4]`.
