### ISSUE TITLE
Rename `clouddrift.dataformat` -> `clouddrift.raggedarray`

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#165]
Not urgent but we should do this before we create tutorials and/or presentations.

**Comment by selipot** [comment]
Because this module desfines uniquely the RaggedArray class? Makes sense. Please implement. Should the `unpack_ragged` be moved to another module such as `clouddrift.analysis`?

**Comment by milancurcic** [comment]
I think so. I initially put it here because I thought it fit together with the ragged stuff, but over time everything else went into analysis, so it makes sense for this one to go to analysis also.
