### ISSUE TITLE
specify fill value for `regular_to_ragged`

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#168]
Should `analysis.regular_to_ragged` includes an optional argument to specify a `_FillValue`? I am thinking of a possible instance of another value than `np.nan` being used such as -999. Same for `analysis.ragged_to_regular`?

**Comment by milancurcic** [comment]
I can imagine that being useful sometimes. NaN should be the default. I think we need to use different functions depending on the fill value. If it's a finite value, we need to check for equality. If it's a NaN, we need to use `np.isnan`. But I think the penalty from the if check here will be minimal, if any.
