### ISSUE TITLE
prune taking an xarray Dataset as an input?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#196]
@milancurcic and I discussed how `prune` could perhaps take a Lagrangian dataset as an input and return a dataset. As an example take the whole hourly GDP, drop the undrogued observations and return whatever is left for both the variables of dimensions `traj` and `obs`. Thoughts @philippemiron ?

**Comment by philippemiron** [comment]
Prune? I'm not sure I understand. This can be done with subset.

```
ds_undrogued = subset(ds, {"drogue_status": False})
```

**Comment by milancurcic** [comment]
I don't understand the drogued/undrogued example either, but I think what @selipot meant was truly prune, but applied to an entire Dataset and not individual DataArrays. Running `prune` on a `Dataset` would return a pruned `Dataset`.

For example use case see cell [15] of the notebook [here](https://github.com/selipot/clouddrift-examples/blob/workshop-2023/notebooks/demo-comm-workshop-2023.ipynb):

```python
# Define new variables by pruning the ones contained in the original xarray dataset: time, longitude, latitude, latitude, velcoity components (ve, vn), and drogue status
min_rowsize = 2 # define the minimum length of segment we want to keep
time,rowsize = prune(ds.time,rowsize,min_rowsize=min_rowsize) 
lon, _ = prune(ds.lon,rowsize,min_rowsize=min_rowsize)
lat, _ = prune(ds.lat,rowsize,min_rowsize=min_rowsize)
ve, _ = prune(ds.ve,rowsize,min_rowsize=min_rowsize)
vn, _  = prune(ds.vn,rowsize,min_rowsize=min_rowsize)
drogue_status, _ = prune(ds.drogue_status,rowsize,min_rowsize=min_rowsize)
```

So, instead, perhaps we could do:

```python
pruned_ds = (ds, min_rowsize=min_rowsize)
```

**Comment by philippemiron** [comment]
I agree, but this could be said for all of the analysis functions 🫠.

**Comment by milancurcic** [comment]
Yes, but for some that would be more useful than for others.

**Comment by selipot** [comment]
> Prune? I'm not sure I understand. This can be done with subset.
> 
> ```
> ds_undrogued = subset(ds, {"drogue_status": False})
> ```

Wow it does ...
