### ISSUE TITLE
Should `rowsize` be renamed to `count`?

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#197]
It occurred to me that in the first sentence of the [Usage page in docs](https://cloud-drift.github.io/clouddrift/usage.html) we link to [a section in CF convention](https://cfconventions.org/cf-conventions/cf-conventions.html#_contiguous_ragged_array_representation) about contiguous ragged arrays. This sections states:

> In this representation, the file contains a count variable, which must be an integer type and
>
> | count(i1) | count(i2) | count(i3) | count(i4) |
> |---|---|---|---|
> | 2 | 4 | 3 | 6 | 
>
> must have the instance dimension as its sole dimension. The count variable contains the number of elements that each feature has. This representation and its count variable are identifiable by the presence of an attribute, sample_dimension, found on the count variable, which names the sample dimension being counted. For indices that correspond to features, whose data have not yet been written, the count variable should  have a value of zero or a missing value.

I don't think that `count` is any better than `rowsize`. However, I do think that following some standard is better than following no standard, and CF is at least to an extent respected in the gridded weather, ocean, and climate world. So it seems to me that if we want to follow CF more closely, we should:

1. Rename `rowsize` to `count`
2. `count` variable should have an attribute `sample_dimension`, which in our case would be `obs`.

This kind of change is uncomfortable to make, but if we decide that it should be made, it would be the sooner the better.

What do you think?

**Comment by milancurcic** [comment]
It looks like we already respect the `sample_dimension` attribute. :+1:

**Comment by philippemiron** [comment]
I'm not opposed to the change. And it's version 0.X.Y for a reason ! I'm not totally sure why I went with `rowsize`...

**Comment by milancurcic** [comment]
`rowsize` made sense to me, but until today I was unaware that CF had a convention about it. :)

**Comment by selipot** [comment]
We can change to `count`. A (2D) array has rows and columns so rowsize makes total sense.

**Comment by philippemiron** [comment]
J. Lilly went with `row_size` [here](https://zenodo.org/record/4421585):

![image](https://github.com/Cloud-Drift/clouddrift/assets/387624/328f9fb9-7598-42f9-9dd3-2f9d661d8019)
