### ISSUE TITLE
How to do a global spaghetti plot with trajectories crossing the dateline or edges on longitude range?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#200]
How to do a global spaghetti plot with trajectories crossing the dateline or edges on longitude range? In jLab, this can be done simply with `cellplot(360,...)`.

**Comment by milancurcic** [comment]
I haven't tried, but I think `segment` could be useful for this:

```python
rowsize = segment(ds.lon, 359, segment(ds.lon, -359))  # or some sensibly large tolerance
# use rowsize to plot contiguous segments or build LineCollections
```

**Comment by philippemiron** [comment]
Yes, something like this should work with `ds.lon360`, otherwise setting the limit to +/-180°.

**Comment by selipot** [comment]
This would create another segment and therefore a line of a different color if the color is randomly assigned by segment. How would the plotting keep the plotting characteristics for each interrupted trajectory?

**Comment by philippemiron** [comment]
Like this:
- retrieve a trajectory
- choose a random color
- split into segments
- add to the segments list
- add len(segments) times the same color

**Comment by milancurcic** [comment]
Another possible approach is to insert a NaN into the array between the two elements that are across the dateline. `plt.plot()` can't draw a line through a NaN.

**Comment by selipot** [comment]
Let's implement this

**Comment by milancurcic** [comment]
Which one?

**Comment by selipot** [comment]
whichever works or makes sense

**Comment by milancurcic** [comment]
OK. I think a function to insert a NaN based on a criterion is reasonable, and it stays away from plotting functionality which I think clouddrift should not deal with. I believe that jLab has a similar function to return a cell-array as a 1-d array with NaN elements as separators, and we discussed implementing it. This specific function could be a special case of that. I'll think about the API.

**Comment by philippemiron** [comment]
I did this example today, we can insert the `nan` using `segments`. Do we need this as a function really?

```
import clouddrift as cd
import matplotlib.pyplot as plt
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter

# example of trajectory
lon = np.array([100, 170, -175, -123, -100, -80, -50, -30, 0, 30, 90, 160, -160, -140], dtype="float")[::-1]
lat = np.array([10, 20, 30, 40, 50, 60, 70, 80, 80, 80, 60, 60, 60, 50], dtype="float")

# find the indices to insert nan using segment
nan_indices = np.cumsum(cd.analysis.segment(lon, 180, rowsize=cd.analysis.segment(lon, -180)))[:-1]

# modify the trajectory
lon_mod = np.insert(lon, nan_indices, np.nan)
lat_mod = np.insert(lat, nan_indices, np.nan)

# plot
fig = plt.figure(dpi=150)
ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())

ax.plot(lon_mod, lat_mod, color='red')
ax.plot(lon, lat, linestyle='dotted', color='black')
ax.xaxis.set_major_formatter(LongitudeFormatter())
ax.yaxis.set_major_formatter(LatitudeFormatter())
ax.set_xlim([-180, 180])
ax.set_ylim([-90, 90])
ax.coastlines(color="black", linewidth=0.5)
```

<img width="773" alt="image" src="https://github.com/Cloud-Drift/clouddrift/assets/387624/2babc62c-eb94-4458-ae5f-7bb62c61a688">

**Comment by selipot** [comment]
We could write a "helping" function inserting the NaN in lat and lon variables. This could be part of a module to help various plotting issues without explicitly providing plotting routines?
