### ISSUE TITLE
switch back to rowsize

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#221]
I would like to propose to switch back to using `rowsize` as the default name for the variable indicating the length of each row of a ragged array.
Pros:
- the term `rowsize` makes sense for an array with rows (think of the ragged array representation/schematic)
- does not interfere with the xarray method `.count` (I just spent 10 minutes trying to figure out why I had an error writing `ds.count` as the input argument of `apply_ragged` whereas I should have written `ds["count"]`)
- the recommendation (from?) to use `count` is not very strong given that the ragged array format is so little used.

**Comment by milancurcic** [comment]
I unassigned @philippemiron so that we don't mistakenly both work on this (it's happened before). Best to only assign one person and ideally the person should self-assign the issue when they start working on it. In other words, think of assignments as "I'm working on this now" rather than "You should be working on this".

**Comment by milancurcic** [comment]
Indeed, since `rowsize`/`count` is used a lot in CloudDrift, it's possible that not being able to use `ds.count` would affect usability for many eventual users.

**Comment by selipot** [comment]
before we move on to anything else, let's switch back to `rowsize` please

**Comment by milancurcic** [comment]
Sure, it's an easy change; will do it next.

**Comment by selipot** [comment]
count has not been changed to `rowsize` all across the `analysis.py` module. I would like this to be changed.

**Comment by milancurcic** [comment]
Do you know where? I thought we both went through the library but something got missed.

**Comment by selipot** [comment]
I only went through the `adapters.gdp*.py` in my PR. I attempted to gp through the rest but started to break things.

**Comment by selipot** [comment]
63 instances of `count` in `analysis.py`

**Comment by milancurcic** [comment]
So, you want the actual use of the word "count" to be replaced with "rowsize"? I understood that only "count" as a member variable on a dataset was problematic.

**Comment by selipot** [comment]
Yes, I want our language to be consistent all across. `count` has a variables is everywhere in the examples as an example.
