### ISSUE TITLE
missing metadata in GDP ragged array files created with clouddrift.adapters.gdp1h

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#223]
Currently I find that the ragged arrays created with `clouddrift.adapters.gdp1h` for v2.00 or version experimental are returning `location_type` to all be True, ie that there are no Argos drifters. I find that the NetCDF files in ftp folders experimental or v2.00 are not consistently of the same format and I suspect some do not contain the location_type global attribute which may be the issue?

Also, the variables `Start_[date,lat,lon]` are missing whereas they do exist in the experimental individual netcdf files.

**Comment by milancurcic** [comment]
I can (attempt to) tackle this after #220 and v0.20.0 release.

**Comment by milancurcic** [comment]
Working on this now.

**Comment by milancurcic** [comment]
Upstream experimental appears empty:  https://www.aoml.noaa.gov/ftp/pub/phod/lumpkin/hourly/experimental/

Is this expected @RickLumpkin @selipot?

**Comment by milancurcic** [comment]
Also, I do find `start_date`, `start_lon`, `start_lat` in individual 6-hourly files, but not hourly (non-experimental).

**Comment by selipot** [comment]
> Also, I do find `start_date`, `start_lon`, `start_lat` in individual 6-hourly files, but not hourly (non-experimental).

Yes since these are new variables

**Comment by selipot** [comment]
> Upstream experimental appears empty: https://www.aoml.noaa.gov/ftp/pub/phod/lumpkin/hourly/experimental/
> 
> Is this expected @RickLumpkin @selipot?

Because the DAC realized that the SST flags were wrong @RickLumpkin must have deleted those ... working with them to put them back.

**Comment by RickLumpkin** [comment]
Yes ... actually the SST flags are right but there's a 0.15 degree offset due to an error in the final stage of our work flow.  Fixed now and new files currently being uploaded to that FTP site.

**Comment by RickLumpkin** [comment]
Done - upload completed, /experimental is repopulated.

**Comment by milancurcic** [comment]
Thank you, @RickLumpkin!
