### ISSUE TITLE
apply_ragged with cartopy

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#227]
There seems to be an issue with using `apply_ragged` with `cartopy`. Please review and have a look at the notebook below where in the last cell I attempt to do just that:

https://github.com/selipot/mosaic-get-started/blob/main/get_started_with_mosaic_icedrift.ipynb

**Comment by milancurcic** [comment]
It's this bit, right?

```
# the following application of apply_ragged crashes my kernel. Why? 
#apply_ragged(ax.plot,[ds.longitude,ds.latitude],ds["count"].values,transform=ccrs.PlateCarree());
```

It's possible that we can't expect this to just work:

> Matplotlib is not thread-safe: in fact, there are known race conditions that affect certain artists. Hence, if you work with threads, it is your responsibility to set up the proper locks to serialize access to Matplotlib artists.
>
> You may be able to work on separate figures from separate threads. However, you must in that case use a non-interactive backend (typically Agg), because most GUI backends require being run from the main thread as well.

https://matplotlib.org/stable/users/faq/howto_faq.html#work-with-threads

**Comment by selipot** [comment]
I am not sure, apply_ragged works with simple matplotlib code. It looks like the inclusion of cartopy causes the problem.
