### ISSUE TITLE
velocity_from_position not behaving as expected

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#229]
I think `velocity_from_position` (and similarly some other related functions) are not behaving as expected. If the time axis is not the last (-1), isn't the intension to return an output of the same size as the input? See the case below where I expect `u` to be the same size as `x`

```
x = np.random.rand(10,20,100)
y = np.random.rand(10,20,100)
t = np.tile(np.arange(0,100),(10,20,1))
u,v = velocity_from_position(x,y,t,time_axis=0)
display(np.shape(x))
display(np.shape(u))

(10, 20, 100)
(100, 10, 20)
```

Maybe a solution is to use `numpy.swapaxes` as I do in my PR #228

**Comment by milancurcic** [comment]
Indeed, that doesn't look correct. The first step is for us to understand why exactly it doesn't work, and why the existing test for N-d didn't catch it.

**Comment by selipot** [comment]
> 

Because the nd-array tests are run for time_axis=-1. They would fail if time_axis!=-1

**Comment by milancurcic** [comment]
Working on this next.
