### ISSUE TITLE
Unittest failing

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#241]
I have been able to reproduce the issue with the tests locally.

```
coverage run -m unittest tests/raggedarray_tests.py
```

I sometimes (~half of the time) gets the following:
```
...
Ran 8 tests in 2.495s

OK
python(87689,0x1de2e1e00) malloc: Double free of object 0x1315fa2b0
python(87689,0x1de2e1e00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      coverage run -m unittest tests/raggedarray_tests.py
```

and this seems to match the error that we see on the GitHub actions.

**Comment by milancurcic** [comment]
Awesome, I'll try to reproduce it as well.

**Comment by philippemiron** [comment]
I think I fixed it. Let me create a proper branch and push here.
