### ISSUE TITLE
Add copy to clipboard button to Sphinx-rendered code blocks

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#254]
Find out how Xarray does it, e.g. https://docs.xarray.dev/en/stable/getting-started-guide/quick-overview.html

**Comment by philippemiron** [comment]
I found this in the getting started page. But now sure how we would do this in the code itself.

```
.. ipython:: python

    import numpy as np
    import pandas as pd
    import xarray as xr
```

**Comment by philippemiron** [comment]
https://github.com/choldgraf/sphinx-copybutton
