### ISSUE TITLE
Use Trusted Publishers to publish to PyPI

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#262]
Two things:
- Trusted Publishers: https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/ are the new prefered way to authenticate from Github Actions (works without password or API Token). Instruction [here](https://docs.pypi.org/trusted-publishers/adding-a-publisher/). And then we can simply change this to the pipeline..
```
obs:
   pypi-publish:
     name: upload release to PyPI
     runs-on: ubuntu-latest
+    permissions:
+      # IMPORTANT: this permission is mandatory for trusted publishing
+      id-token: write
     steps:
       # retrieve your distributions here

       - name: Publish package distributions to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          username: __token__
-          password: ${{ secrets.PYPI_TOKEN }}
```
- have to activate 2 factor authentification to use this feature. Should I do it? Right now the pypi `clouddrift` user is my email address.

@selipot @milancurcic

**Comment by selipot** [comment]
I did it for myself. Not too cumbersome in the end since I am almost always signed in.

**Comment by milancurcic** [comment]
I also have it on. The proposed change looks good.

**Comment by philippemiron** [comment]
I'm wondering if we need the `clouddrift` user on `pypi`. Maybe I just create an account for myself and delete the "clouddrift" account.

**Comment by selipot** [comment]
I never followed that topic so I do not know @philippemiron (or understand)

**Comment by milancurcic** [comment]
It doesn't really matter; you can probably just rename the clouddrift user to what you want to use personally. I only use my personal account.

**Comment by philippemiron** [comment]
I will see if I can rename it. Otherwise I will use my personal account to manage `clouddrift`.

**Comment by philippemiron** [comment]
Should be done now.. But let's keep this open until we push a new release. I deleted both`clouddrift` accounts on `test.pypi.org` and the `pypi.org`. And I added myself as one of the owner on the project.

**Comment by philippemiron** [comment]
Pipeline ran and updated correctly `0.22.0`, so I will close this.
