### ISSUE TITLE
`rowsize_to_index`

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#265]
This:

```python
np.insert(np.cumsum(ds["rowsize"].values), 0, 0)
```

seems to pop-up very often that it seems to me that this:

```python
def rowsize_to_index(rowsize):
    return np.insert(np.cumsum(rowsize), 0, 0)
```

would be useful to have.

What do you think?

**Comment by philippemiron** [comment]
All for it if it's more than 2 times in the code :D
