### ISSUE TITLE
different `tmp_path` in `adapters.gdp1h` for regular and experimental sources

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#285]
Currently, the path where individual NetCDF files are downloaded is set as :

```
GDP_TMP_PATH = os.path.join(tempfile.gettempdir(), "clouddrift", "gdp")
```
for both the regular and the experimental sources. This could lead to issues (or headaches) if someone is simultaneously using `GDP_DATA_URL` and `GDP_DATA_URL_EXPERIMENTAL` without clearing that folder or specifying manually a folder.

I suggest that to set the path to:
```
GDP_TMP_PATH = os.path.join(tempfile.gettempdir(), "clouddrift", "gdp_exp")
```
`if url == 'GDP_DATA_URL_EXPERIMENTAL'`.

**Comment by selipot** [comment]
I like it!

**Comment by selipot** [comment]
Should we add this feature to #282 ?

**Comment by philippemiron** [comment]
We can, I was going to add it but it requires a bit more thoughts with the current design.
