### ISSUE TITLE
Proposal to break down `cd.analysis`

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#288]
The `cd.analysis` module currently provides 12 functions:

* apply_ragged(func, arrays, rowsize, *args[, ...])
* chunk(x, length[, overlap, align])
* mask_var(var, criterion)
* position_from_velocity(u, v, time, x_origin, ...)
* prune(ragged, rowsize, min_rowsize)
* ragged_to_regular(ragged, rowsize[, fill_value])
* regular_to_ragged(array[, fill_value])
* rowsize_to_index(rowsize)
* segment(x, tolerance[, rowsize])
* subset(ds, criteria[, id_var_name, ...])
* unpack_ragged(ragged_array, rowsize[, rows, ...])
* velocity_from_position(x, y, time[, ...])

`analysis` is not a descriptive name and was initially started as a catch-all. I propose break the functions up by theme and name their modules accordingly.

1. Move `position_from_velocity` and `velocity_from_position` into `cd.kinematics`.
2. Move `apply_ragged`, `chunk`, `prune`, `ragged_to_regular`, `regular_to_ragged`, `rowsize_to_index`, `segment`, `subset`, `unpack_ragged` to `cd.ragged`.
3. Make `mask_var` a private `_maks_var` in `cd.ragged`.
4. Rename `cd.ragged.unpack_ragged` -> `cd.ragged.unpack`.

Module name ideas welcome.

**Comment by selipot** [comment]
Yes to all. 

Where would `subset` go? Maybe its own module?

Love `kinematics` as a module name. I think `inertial_oscillations_from_positions` and `corrected_positions_from_displacements` from #286 could fit in there.

Future possible functions related to dynamical model could go in a `dynamics` model such as `stokes_drift_from_wave_spectrum` or is that a kinematic model :)

**Comment by milancurcic** [comment]
I think `subset` fits in `ragged` because it assumes the presence of `traj` dimension and `rowsize` variable in the dataset. I think `subset` could be "tricked" into subsetting a regular (non-ragged) dataset, but ultimately ragged datasets are its main use case.
