### ISSUE TITLE
best way to create a clouddrift kernel for jupyter lab?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#30]
What's the best way to create a clouddrift kernel for jupyter lab?

After creating the clouddrift environment with conda I had to
1. `conda activate clouddrift`
2. `conda install ipython ipykernel`
3. `ipython kernel install --user --name=clouddrift`
4. Then in another environment with jupyter lab installed, launch jupyter lab, then select the clouddrift kernel within jupyter lab.

Is this the right way to go about this? That is for using a jupyter lab/notebook to run some of the clouddrift examples locally?

**Comment by philippemiron** [comment]
Yes, this is the way to do it for any environment. Or, if you prefer:

```
conda activate clouddrift
conda install jupyterlab
jupyter-lab
```
