### ISSUE TITLE
subset by row/segment?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#305]
Could we add a functionality to `subset` or another function `subset_rows` which would subset by ... rows? One might argue that one could use the `ID` criteria but after segmenting with `segment` as an example and changing the rows this does not work anymore.

It could be
```
ds_subset = subset(ds,rows=[10,35, 45])
```

**Comment by philippemiron** [comment]
But how are the IDs after using segments? Can you put the code of what you are doing.

**Comment by selipot** [comment]
```
ds = xr.open_dataset("/Users/selipot/Data/awss3/latest/gdp-v2.01.zarr",engine="zarr",decode_times=False)
segment_size = segment(ds["time"],3600,ds["rowsize"])
# length of segment_size is 100235
segment_index = rowsize_to_index(segment_size)
```

Now I would like to subset let's say, the second segment that shares and `ID` with the first and third etc segments:

```
ds_subset = subset(ds,rows=[1])
```

And how to subset rows that have a given length or belong to a certain interval? Could we specify:
```
ds_subset = subset(ds,rowsize=[0,10]) # subset rows of length up to 10

ds_subset = subset(ds,rowsize=[5,10]) # subset rows of length between 5 and 10

ds_subset = subset(ds,rowsize=[10 np.inf]) # subset rows of length 10 and up

```

**Comment by milancurcic** [comment]
I haven't tried but I think the 3rd option should work because `rowsize` is a variable, so perhaps

```python
ds_subset = subset(ds, {"rowsize": (0, 10)}) # subset rows of length up to 10
ds_subset = subset(ds, {"rowsize": (5, 10)}) # subset rows of length between 5 and 10
ds_subset = subset(ds, {"rowsize": (10, np.inf)}) # subset rows of length 10 and up
ds_subset = subset(ds, {"rowsize": 15}) # subset rows of exactly length 15
```

Of course, this is no substitute for subsetting a specific row.

**Comment by philippemiron** [comment]
For the first thing, you could do something like this:

```
segment_id = np.zeros_like(ds.ids)
start = 0
for i in range(0, len(segment_size)):
    end = start + segment_size[i]
    segment_id[slice(start, end)] = i
    start = end

ds["segment_id"] = segment_id

# then extra any segment
cd.ragged.subset(ds, {"segment_id": 0})
```

And for the second thing, there are 3 ways of using `subset`:
- with a single value -> `drogue: True` for example
- with a list -> `id: [0, 1, 2]` to select some values
- with a tuple -> `lon: (0, 10)` to extract a range of data

so what Milan wrote should work to extra lines with a specific length using the `rowsize` variables.
