### ISSUE TITLE
catch failed execution in apply_ragged

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#306]
I think it would be beneficial for `apply_ragged` to be able catch a failed execution, i.e. to continue the execution even after it fails for a given row. As an example trying to apply `inertial_oscillation_from_position` on the global GDP with `apply_ragged` will not always work for all segments but that should not stop the application. Apply ragged would then return something like filling values where it fails? I used GitHUb Copilot to find that some a method like `add_done_callback` could be added to the future object perhaps? Then how to return filled values of the expected shape etc?

**Comment by philippemiron** [comment]
Maybe something like this:

```
def try_submit(func, x, *args, **kwargs):
    try:
        return executor.submit(func, *x, *args, **kwargs)
    except:
        return np.full_like(x, fill_value)

res = [try_submit(func, x, *args, **kwargs) for x in iter]
```

**Comment by philippemiron** [comment]
I think it's not exactly correct since `x` can be a list of ragged arrays, maybe it should be `x[0]`...

**Comment by selipot** [comment]
This current solution works because I know what `inertial_oscillations_from_positions` need to return, i.e a tuple of arrays of length equal to the input. But I suspect it would not work with a different type of expected outputs. How to automatically return the correct size/shape/type with fill values? Note the `try_submit` function returns `future.result()`, not `future`.
```
def try_submit(func, x, *args, **kwargs):
        try:
            future = executor.submit(func, *x, *args, **kwargs)
            return future.result()
        except:
            return (np.full_like(x[0], np.nan),np.full_like(x[0], np.nan))
    
    # parallel execution
    res = [try_submit(func, x, *args, **kwargs) for x in iter]
    res = [r for r in res]
```

copilot suggested for the except to return the following but that does not work
```
return np.full_like(x[0], np.nan) if not isinstance(x[0], Iterable) else [np.full_like(xi,np.nan) for xi in x[0]]
```

in python is there a method to return the type/shape of a function output such as `myfunction.outputargument`?

**Comment by selipot** [comment]
Maybe the solution is for individual functions such as `inertial_oscillations_from_positions` to initialize the output with fill values and return that in case it fails?

**Comment by philippemiron** [comment]
True.  I'm not sure how that could be generalized for any functions without knowing what would be returned.

**Comment by philippemiron** [comment]
And this:

```
return np.full_like(x[0], np.nan) if not isinstance(x[0], Iterable) else [np.full_like(xi,np.nan) for xi in x[0]]
```

would work as long as x[0] is fine..

**Comment by milancurcic** [comment]
We shouldn't catch in `apply_ragged` because a user may want an exception raised by the function.

For a specific case with `inertial_oscillation_from_position`, you can wrap it in a `try/except` block and pass that as a function to `apply_ragged`.

**Comment by selipot** [comment]
I think that's the way to go, thank you @milancurcic
