### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#32]
The package is now available on [pypi](https://pypi.org/project/clouddrift/) but a few steps are required to put this into a conda feedstock. I am waiting for awkward array >=1.9.0 ([link](https://github.com/conda-forge/awkward-feedstock/pull/83#issuecomment-1251723796)) to be available in conda, which would simplify a lot building the package and setting up the environment. This should also fix the binder environment.

Note that the clouddrift library is using awkward array v2, which officially should be out by the end of Q4 2022. It is accessed using `import awkward._v2 as ak` for now, and a lot of this is only available from >1.8.0. Their [conda package](https://anaconda.org/conda-forge/awkward) is currently on 1.8.0, but it is evolving pretty fast!

**Comment by philippemiron** [comment]
I have pushed the staged-recipes `clouddrift` branch of the `staged-recipes` [repo](https://github.com/Cloud-Drift/staged-recipes) to `conda-forge`. See the PR, https://github.com/conda-forge/staged-recipes/pull/21825.

I applied some modifications which fix the linux and windows builds, but there is an issue with the macOS build. I'll try to figure it out, or maybe someone give me some advice soon.

**Comment by philippemiron** [comment]
I just rebuild and it worked, so I guess the macOS issue was a server related one. I added both @milancurcic and @selipot as maintainers. You have to post a message on the PR because they want: "GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there."

**Comment by selipot** [comment]
Which PR @philippemiron?

**Comment by milancurcic** [comment]
Thanks @philippemiron. Before I agree to maintain there in conda-forge PR, can you explain (maybe again, but I don't recall that we discussed it) what is the concrete benefit of having this in conda-forge? We can already install clouddrift in conda envs using pip.

**Comment by selipot** [comment]
My two cents: make it easier for users, more versatile perhaps? Expand the exposure of the library? What about windows machines?

**Comment by milancurcic** [comment]
I can try a Windows build soon.

I don't find the ease argument compelling--the difference in instructions is one line vs. two lines.

But the maintenance cost is real--we're committing to support a second build system (that we can already build in) in perpetuity. I don't argue that we shouldn't support conda-forge, but I think we should have good and concrete reasons for doing something that adds cost.

What do you think about waiting for one user that asks for a conda-forge recipe?

**Comment by milancurcic** [comment]
Another option, @philippemiron if you're willing to maintain the conda-forge recipe, I'm all for it.

**Comment by philippemiron** [comment]
Most people don't only use `pip` to create their environment since it doesn't take care of installing system libraries (for example netCDF libraries required for xarray). Conda does all this and it's also OS-agnostic. So I think having the package in `conda` makes it simpler for everyone that want `clouddrift` by simply adding the library in their main working environment.

Also, it requires updating/maintaining the recipe the file yes, but it's based on the `pip` package so not a lot of work to be done. And there is a way to make the upload to `pypi` and the conda recipes automatically from a GitHub actions on change of version.

**Comment by milancurcic** [comment]
I'm not asking about a non-conda environment, nor I'm asking about differences between pip and conda. I'm asking what concretely do we gain with this. On Linuxes you can simply do (in your Conda env):

```
pip install clouddrift
```

(on Linux at least, netCDF4 Python package ships with its own NetCDF dynamic library file; I assume it's the same for macOS and Windows based on the wheel listing [here](https://pypi.org/project/netCDF4/#files); if so, the system library argument is not relevant here)

Have you tried the above on macOS? If it doesn't work, can you open an issue? I would try it but I don't have a macOS.

On Windows, I'll give it a try.

On a niche system like ppc64 that doesn't have pre-built wheels for NetCDF and pyarrow, we need to do:

```
conda install netCDF4 pyarrow
pip install clouddrift
```

So, you get the idea. I'm asking what is the specific problem that we have and what is the cost of the simplest solution that we can implement.

I can certainly appreciate and acknowledge that it's nice for Conda users to be able to just type `conda install clouddrift` instead of `pip install clouddrift`.

But I'm cautious about myself committing to maintain this when we have a relatively short runway (~1.5 yrs of part-time for me) to implement various analysis functions and acquire users.

> And there is a way to make the upload to pypi and the conda recipes automatically from a GitHub actions on change of version.

This sounds like it would be a great way to solve this. Can you tackle it?

**Comment by philippemiron** [comment]
Ok I'll do it.

> I'm not asking about a non-conda environment, nor I'm asking about differences between pip and conda. I'm asking what concretely do we gain with this. On Linuxes you can simply do (in your Conda env):
> 
> ```
> pip install clouddrift
> ```
> 
> (on Linux at least, netCDF4 Python package ships with its own NetCDF dynamic library file; I assume it's the same for macOS and Windows based on the wheel listing [here](https://pypi.org/project/netCDF4/#files); if so, the system library argument is not relevant here)
> 
> Have you tried the above on macOS? If it doesn't work, can you open an issue? I would try it but I don't have a macOS.
> 
> On Windows, I'll give it a try.
> 
> On a niche system like ppc64 that doesn't have pre-built wheels for NetCDF and pyarrow, we need to do:
> 
> ```
> conda install netCDF4 pyarrow
> pip install clouddrift
> ```
> 
> So, you get the idea. I'm asking what is the specific problem that we have and what is the cost of the simplest solution that we can implement.
> 
> I can certainly appreciate and acknowledge that it's nice for Conda users to be able to just type `conda install clouddrift` instead of `pip install clouddrift`.
> 
> But I'm cautious about myself committing to maintain this when we have a relatively short runway (~1.5 yrs of part-time for me) to implement various analysis functions and acquire users.
> 
> > And there is a way to make the upload to pypi and the conda recipes automatically from a GitHub actions on change of version.
> 
> This sounds like it would be a great way to solve this. Can you tackle it?

I can do it.

**Comment by selipot** [comment]
Thank you @philippemiron for your contribution! Can we close this issue?

**Comment by milancurcic** [comment]
Fantastic, thank you!

**Comment by philippemiron** [comment]
Let's close it when the package is available.
