### ISSUE TITLE
GLAD dataset structure?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#323]
I do not understand the organization of the GLAD dataset: 3 dimensions `(obs, index, traj)` and 2 coordinates `obs(index)` and `traj(traj)`?  Why isn’t it organized like let’s say the gdp1h() datasets with 2 dimensions `(traj,obs)`  and coordinates `(ids(obs),time(obs))`?

**Comment by selipot** [comment]
![screenshot_2023-11-14_at_10 25 11___am_720](https://github.com/Cloud-Drift/clouddrift/assets/7576346/4f19f790-5719-48ff-a9bf-b26fdaa44a2c)

**Comment by selipot** [comment]
Actually no, I installed from `pr/philippemiron/321`. Let me try otherwise.

**Comment by selipot** [comment]
Same thing from main branch and reinstalling clouddrift
<img width="1254" alt="Screenshot 2023-11-14 at 11 49 35 AM" src="https://github.com/Cloud-Drift/clouddrift/assets/7576346/14b18be3-4c87-4a24-9208-154d4e760a49">

**Comment by philippemiron** [comment]
I'm also getting the index. I was getting this dimension with the YoMaHa datasets. I think it's created with:
```
ds = xr.Dataset.from_dataframe(df)
```

**Comment by milancurcic** [comment]
Here I have:

pandas==2.1.0
xarray==2023.8.0

I'll investigate.

**Comment by milancurcic** [comment]
This renames the dim "index" to "obs" and drops the "index" variable, among few other things. 

https://github.com/Cloud-Drift/clouddrift/blob/a27e421ba9be42d8da2d25149920ac3fdf9381d4/clouddrift/adapters/glad.py#L64-L69

Now that I play with it again, the `obs=ds.obs` part may be unnecessary so the above could be

```python
 ds = ( 
     ds.swap_dims({"index": "obs"}) 
     .assign_coords(traj=traj) 
     .assign({"rowsize": ("traj", rowsize)}) 
     .drop_vars(["id", "index"]) 
 ) 
```
