### ISSUE TITLE
python 3.10 upgrade

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#335]
Going from 3.9 to 3.10, there were significant convenience updates to Python's typing syntax:

* Can use built-in types (`list`, `dict`, `tuple`...) for type hints rather than importing them from `typing` (`List`, `Dict`, `Tuple`)
* Using `Optional` not necessary
* `|` instead of union

For example, in Python 3.9 (our current code)

```python
from typing import Tuple, List, Optional, Union
import numpy as np
import xarray as xr

def f(
    x: Union[List, np.array, xr.DataArray],
    n: Optional[int] = 0
) -> Tuple[int, float]:
    ... 
```

becomes

```python
import numpy as np
import xarray as xr

def f(
    x: list | np.array | xr.DataArray,
    n: int = 0
) -> tuple[int, float]:
    ... 
```

The advantages are developer convenience, more concise syntax, and requiring users to use a more recent Python version.

A disadvantage is requiring users to use a more recent Python version.

**Comment by philippemiron** [comment]
I wonder how many people uses 3.9? I see that python version supports for numpy, xarray, pandas is all set at `python>=3.9`.. I was trying to find discussion on their end to pass to 3.10 but didn't find anything either.

**Comment by philippemiron** [comment]
I would say let's go for it. Just for the simplicity of typing it's worth it.
