### ISSUE TITLE
sum(rowsize) in apply_ragged

### ISSUE THREAD

**Issue by vadmbertr** [Cloud-Drift/clouddrift#342]
Hi,

Thanks for this very useful library.

I am using version 0.28.0 of clouddrift, and version 2023.12.0 of xarray. Version 3.9.6 of Python on macOS Sonoma 12.4.

I wanted to apply a function over all the trajectories from the `gdp1h` dataset and I found a strong bottleneck in the `apply_ragged` function. The sanitary check for `rowsize` calls `sum(rowsize)`. I understand that it allows to handle `rowsize` of type `list`, but if `rowsize` is a `xr.DataArray` (or a `np.ndarray`) it is **considerably** slower than calling `rowsize.sum()`. On my MacBook, `gdp1h.rowsize.sum()` takes less than a second, while `sum(gdp1h.rowsize)` does not return after 10 minutes.

One can reproduce this behavior with:
```
import clouddrift as cd

gdp1h = cd.datasets.gdp1h()
sum(gdp1h.rowsize)  # takes forever
gdp1h.rowsize.sum()  # takes less than a second
```

Interestingly, calling `gdp1h.rowsize.sum()` before `sum(gdp1h.rowsize)` allows to get a result in a few seconds (with my laptop). Therefore, an easy workaround is to call `gdp1h.rowsize.sum()` before calling `apply_ragged` with `gdp1h.rowsize` as argument.

Fixing it should be easy by casting `rowsize` to a `np.ndarray` if it is a `list` (or a `tuple`):
```
    if type(rowsize) in [list, tuple]:  # or if type(rowsize) == list:
        rowsize = np.array(rowsize)
```
And then replacing
```
    for arr in arrays:
        if not sum(rowsize) == arr.shape[axis]:
```
with:
```
    for arr in arrays:
        if not rowsize.sum() == arr.shape[axis]:
```

If you guys agree on the fix, I can fork, fix it in a branch, and open a pull request.

Vadim

**Comment by selipot** [comment]
Yes, it looks like I can reproduce the behavior you describe. Thank you for identifying this issue and be willing to contribute. Please go ahead and submit a pull request!

**Comment by vadmbertr** [comment]
Will do in the afternoon. Using `np.sum(rowsize)` is actually even simpler than `rowsize.sum()` as it does not required explicit casting beforehand.

**Comment by milancurcic** [comment]
Thanks, Vadim. I can't seem to reproduce this, albeit I'm not on a Mac but Ubuntu.

```python
In [1]: from clouddrift.datasets import gdp1h

In [2]: ds = gdp1h()

In [3]: sum(ds.rowsize)  # initial download of remote data
Out[3]: 
<xarray.DataArray 'rowsize' ()>
array(197214787)

In [4]: %timeit sum(ds.rowsize)
61.6 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [5]: %timeit np.sum(ds.rowsize)
61.2 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [6]: %timeit ds.rowsize.sum()
57.5 µs ± 247 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

In the reproducer that you posted:

```python
import clouddrift as cd

gdp1h = cd.datasets.gdp1h()
sum(gdp1h.rowsize)  # takes forever
gdp1h.rowsize.sum()  # takes less than a second
```

the line `sum(gdp1h.rowsize)  # takes forever` will spend time downloading remote data through the network, whereas the line `gdp1h.rowsize.sum()` will simply run a sum in local data.

Can you please run the test with the snippet that first downloads the data and then times the two functions on local data?

Either way, it's probably harmless to apply your PR to replace `sum` with `np.sum` since `np.sum` appears to be as efficient on my end, but I'd like us to first understand whether this is a real issue on macOS, or a false positive.

**Comment by vadmbertr** [comment]
Hi Milan,

The thing is that `sum(gdp1h.rowsize)` (with my system versions) litteraly takes more than 10 minutes to complete if the data has not been downloaded first. So, when running your snippet, the third call hangs.

To summarize, here are the results of the two snippets versions:

```
In   [1]: from clouddrift.datasets import gdp1h
       ...: import numpy as np

In   [2]: ds = gdp1h()

In   [3]: sum(ds.rowsize)  # hangs for minutes (at least)
```

```
In   [1]: from clouddrift.datasets import gdp1h
       ...: import numpy as np

In   [2]: ds = gdp1h()

In   [3]: np.sum(ds.rowsize)  # less than a second
Out[3]: 
<xarray.DataArray 'rowsize' ()>
array(197214787)

In   [4]: %timeit sum(ds.rowsize)
2.1 s ± 17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In   [5]: %timeit np.sum(ds.rowsize)
62.9 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In   [6]: %timeit ds.rowsize.sum()
60.5 µs ± 87 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

**Comment by milancurcic** [comment]
OK, thanks for confirming that. I can see that your `In [4]` cell is unreasonably slow. I'll mark your PR as good to go forward.
