### ISSUE TITLE
GDP data adapters need to contain two more global attributes

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#344]
In the case of the GDP, NCEI requests that the following global attributes be added: `time_coverage_start` or `time_coverage_end`. This could be done in either of two ways:

1. Collect these attributes from the individually gathered NetCDF files and pick the first of `time_coverage_start` and last of `time_coverage_end` for the ragged array file
2. Determine the minimum and maximum values of the ragged array variable `time` and assign them to   `time_coverage_start` and `time_coverage_end`, respectively.

**Comment by philippemiron** [comment]
I would vote for #1, that way we are sure that we don't introduce different values from the source.

**Comment by milancurcic** [comment]
#2 is easier to implement, and if the resulting value is different from the source, it would mean that the source value is incorrect, which seems like it would be important to know.

**Comment by philippemiron** [comment]
Can't we just add this to the gdp adapters as new variables to bring to the ragged arrays if there are already in the files?

**Comment by philippemiron** [comment]
I guess the question is do we also want the `time_coverage_start` and `time_coverage_end` for each trajectory to be `[traj]` variable? And then we take the minimum and set it as a global variable? Or we only add this to the global variable? 

After giving it some thought, my opinion is now that it's not that useful to have this for each trajectory (very easy to calculate..) so we could just add min(time) max(time) as global attributes (#2).

**Comment by selipot** [comment]
Yes, I believe we want it to be global attributes
