### ISSUE TITLE
Replace `for` loop with `np.isin` in `ragged._mask_var`

### ISSUE THREAD

**Issue by vadmbertr** [Cloud-Drift/clouddrift#346]
Hi,

I noticed that the function `_mask_var` in the module `ragged` can be quite slow if the criterion is a large list (or `np.ndarray` / `xr.DataArray`). Instead of the `for` loop, the numpy `isin` function could be used here to improve performances.
Here is small snippet demonstrating it:

```python
import numpy as np
import xarray as xr

def mask_for_loop(var, criterion):
    mask = xr.zeros_like(var, dtype=bool)
    for v in criterion:
        mask = np.logical_or(mask, var == v)
    return mask

def mask_isin(var, criterion):
    return np.isin(var, criterion)

var = xr.DataArray(np.random.randint(1, 1000, size=int(1e5)))
criterion = xr.DataArray(np.random.randint(1, 1000, size=int(1e4)))

mask_for_loop_val = mask_for_loop(var, criterion)
mask_isin_val = mask_isin(var, criterion)
np.all(mask_for_loop_val==mask_isin_val)
Out: 
<xarray.DataArray ()>
array(True)

%timeit mask_for_loop(var, criterion)
3.84 s ± 23.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit mask_isin(var, criterion)
282 µs ± 8.94 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

If you agree on it I can open a PR.

Vadim

**Comment by philippemiron** [comment]
Don't you need the for loop for criterion like:

`{"lon": (-98, -78), "lat": (24, 31)}`

**Comment by vadmbertr** [comment]
If I follow you correctly, for such criterion (`tuple`), `mask = np.logical_and(var >= criterion[0], var <= criterion[1])` will get executed, not the `for` loop.

**Comment by philippemiron** [comment]
But since we don't know how many elements are part of the criterion, we used a for loop to create the mask.

``
mask = xr.zeros_like(var, dtype=bool)
for v in criterion:
   mask = np.logical_or(mask, var == v)
```

**Comment by vadmbertr** [comment]
Yes of course. But it could be done more efficiently by using [`np.isin`](https://numpy.org/doc/stable/reference/generated/numpy.isin.html) (or [`np.in1d`](https://numpy.org/doc/stable/reference/generated/numpy.in1d.html)) that will take `var` as first argument, and `criterion` as second argument. 

From the docs on `np.isin`:

> Calculates `element in test_elements`, broadcasting over `element` only. Returns a boolean array of the same shape as `element` that is `True` where an element of `element` is in `test_elements` and `False` otherwise.

**Comment by philippemiron** [comment]
Sorry, I should have looked at the code first, this is just to replace the part that takes care of a criteria defined by a `list` where we want to match each item.

Let's do it.
