### ISSUE TITLE
Allow `Callable` criterion in `ragged.subset`

### ISSUE THREAD

**Issue by vadmbertr** [Cloud-Drift/clouddrift#347]
In my opinion, it could be useful to subset based on the mask return by a function applied over trajectories.

Possible usecases could be:
- filter in one shot trajectories based on more complex geometries than bounding boxes. For example, keep trajectories of drifters released in the Mediterranean Sea, whithout the ones of the Bay of Biscay or the Black Sea, see:
![med_sea](https://github.com/Cloud-Drift/clouddrift/assets/36510417/bce0430a-545f-4a4e-abe4-c54d58588e7c)
- filter trajectories' positions based on their time differences to the first recorded time of the trajectory (for example, keep positions every 24h after the first recorded time).

It would involved some modifications to the functions `subset` and `_var_mask`, but I think they would not break any current behavior.

What are your thoughts on this? I can propose some snippets to the mentioned usecases and possible implementations if you want.

**Comment by philippemiron** [comment]
I guess you could already do this like this with a function `func()` returning a boolean for the observations.

`subset(ds, {"obs", np.arange(ds.sizes["obs"])[func()]})`

this functionality was just recently added https://github.com/Cloud-Drift/clouddrift/pull/338.

**Comment by vadmbertr** [comment]
I'm not sure to understand your example.

Let's say I want to downsample all my trajectories, and retain only observations made at the same time of the day as the one of the first recorded datetime. Since the number of observations to retain will vary across trajectories, I have to first use `apply_ragged`:
```python
import clouddrift as cd

def daily_masking(
        traj_time: xr.DataArray
) -> np.ndarray:
    traj_time = traj_time.astype("float64")
    traj_time /= 1e9  # to seconds
    traj_time -= traj_time[0]  # start from 0
    mask = (traj_time % (24*60*60)) == 0  # get only obs at the same time as the first one
    rowsize = int(mask.sum())  # the number of obs per traj has to be updated
    return mask, rowsize

gdp1h = cd.datasets.gdp1h()
daily_mask, daily_rowsize = cd.ragged.apply_ragged(daily_masking, gdp1h.time, gdp1h.rowsize)
```

Then, I order to subset, either I do it "manually", or I use `subset` with the functionality introduced by https://github.com/Cloud-Drift/clouddrift/pull/338 as you mentioned:
```python
# manually
daily_gdp1h = gdp1h.isel({"traj": np.ones_like(gdp1h["traj"], dtype=bool),  # needed to copy DataArrays (and `rowsize`)
                                           "obs": daily_mask})
daily_gdp1h["rowsize"].values = daily_rowsize

# using `subset`
daily_gdp1h = cd.ragged.subset(gdp1h, {"obs": gdp1h["obs"][daily_mask]})
```

Knowing how to achieve this kind of subsetting I can live with it, but it feels to me that (for an user) it will be more natural and easier to do:
```python
daily_gdp1h = cd.ragged.subset(gdp1h, {"time": daily_masking})
```

Plus, currently, `daily_gdp1h = cd.ragged.subset(gdp1h, {"obs": gdp1h["obs"][daily_mask]})` hangs on my laptop because of https://github.com/Cloud-Drift/clouddrift/issues/346. And in general, the `subset` feels sub-optimal bacause it i) masks ii) selects `obs` iii) tests if every `obs` of the `Dataset` should be selecting by searching its "id" in an array using a `for` loop.

**Comment by vadmbertr** [comment]
Yes, exactly!

**Comment by milancurcic** [comment]
I think allowing a `Callable` would be a great addition. :+1:
