### ISSUE TITLE
`trajectory` or `row`?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#351]
For the `ragged` module (and perhaps other modules) I am wondering if we should try to unify the language. We use a mix of `trajectory` and `row` and their plural forms. Because clouddrift addresses any ragged array dataset we could  stay more general. Since we settled on `rowsize`, we could modify as follows:

- `full_trajectories` -> `full_rows` 
- trajectory -> `row`
- `rowsize_var_name` -> `row_var_name`
- ...

And in docstrings where we are obviously dealing with Lagrangian trajectories or segments we could explicitly write `trajectory`. Thoughts?

**Comment by philippemiron** [comment]
I agree.

Better breaks things early and make it more uniform/easier to remember.
