### ISSUE TITLE
consolidate GDP DAC URLs

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#353]
It looks like the ragged array dataset for the 6-hourly product are now found at `https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/`. This implies we need to modify `clouddrift.datasets.gdp6h()`

Yet I do not know where to find the corresponding netcdf files which used to be at `https://www.aoml.noaa.gov/ftp/pub/phod/lumpkin/netcdf/`?

**Comment by RickLumpkin** [comment]
Adding the individual files now to that ftp site.
