### ISSUE TITLE
Update environment.yml

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#36]
In light of the recent packaging updates for awkward and adding clouddrift to conda-forge.

See [this thread](https://github.com/Cloud-Drift/clouddrift/pull/35#discussion_r988224027) for context.

**Comment by philippemiron** [comment]
I believe you are correct, `clouddrift` should not be present in the environment file.

```
name: clouddrift
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - matplotlib>=3.5.2
  - numpy>=1.22.4
  - pandas>=1.4.2
  - xarray>=2022.3.0
  - netcdf4>=1.5.8
  - pyarrow>=8.0.0
  - zarr>=2.11.3
  - numba>=0.53.1
  - tqdm>=4.64.0
  - fsspec>=2022.3.0
  - awkward>=1.9.0
```
would be correct to generate the dependencies required to run the examples, and then you can `pip install awkward`. 

In this branch, https://github.com/Cloud-Drift/staged-recipes/tree/clouddrift, you can see the `recipes/clouddrift/` folder with the `meta.yaml` containing the instruction to generate the conda package.

Right now the dependencies there are slightly different, for example, it does not include `matplotlib` and `fsspec` as it is not required for the package itself. We should take a look at the best way to do this before pushing the branch to `conda-forge`.

**Comment by philippemiron** [comment]
I think we can close this; we have modified the environment following #98.
