### ISSUE TITLE
GDP 6H dataset - Operation timed out

### ISSUE THREAD

**Issue by vadmbertr** [Cloud-Drift/clouddrift#363]
Hi!

I'm getting timeout errors with the GDP 6H dataset (using clouddrift 0.30.0, python 3.9, macOS 14.2).
For example:

```python
import clouddrift as cd
import numpy as np

# I can open the dataset:
gdp6h = cd.datasets.gdp6h()
gdp6h

# But the following fails with:
# curlcode: (28)Timeout was reached : Operation timed out after 100024 milliseconds with 35960000 out of 359926208 bytes received
{"lon": int(np.isnan(gdp6h.lon).sum()), "lat": int(np.isnan(gdp6h.lat).sum()), "time": int(np.isnat(gdp6h.time).sum())}
```

Can you replicate it on your side?
Vadim

**Comment by philippemiron** [comment]
I confirm the same issue. I just did, 
```
import clouddrift as cd
gdp6h = cd.datasets.gdp6h()
gdp6h.time.values
curlcode: (28)Timeout was reached : Operation timed out after 100787 milliseconds with 94192000 out of 359926208 bytes received
```
and getting the same error. My guess is that NOAA server is not stable enough..

**Comment by selipot** [comment]
I get the same errors yet I am able to download the file directly

<img width="1035" alt="Screenshot 2024-01-30 at 5 43 27 AM" src="https://github.com/Cloud-Drift/clouddrift/assets/7576346/3c777c5d-ed88-452f-8d30-f184908ff8aa">

One solution I could explore is to put the 6-hour file on the AWS bucket as well.  The bucket is supposed to be for the hourly files only but I can clear with the people managing the bucket.

**Comment by kevinsantana11** [comment]
This was addressed in a recent PR
