### ISSUE TITLE
Should we commit executed Jupyter notebooks?

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#37]
Currently, the notebooks under examples/ are committed with cleared cells.

Should we commit executed notebooks? An advantage to doing this is that the notebook becomes readable in the browser, no need to run it. This is for people who want to get get a taste of it without having to set it up locally.

A disadvantage is a little more burden on maintenance. If the output of the cells changes (e.g. due to the change of the implementation or the API), the notebooks would need to be updated as well. If there are graphics in the notebooks (and there aren't yet), then the PNG images are encoded as strings which become part of the notebook JSON file. This can significantly increase the size of the git repo, although not in any problematic way.

All this said, I'm in favor of committing executed notebooks to the repo. I'm curious what you think.

**Comment by selipot** [comment]
I do agree that executed notebooks are good when these are in their *final* form. Before that stage, I have found annoying/confusing to collaborate on the writing and editing of these notebooks. What's the best way to correct let's say a small typo?
