### ISSUE TITLE
change to  `clouddrift.adapters.gdp1h()`

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#372]
We need to make sure that `clouddrift.adapters.gdp1h()`  generates a dataset with new convention  coordinate variables `id(traj)` and `time(obs)` instead of `ids(obs)` and `time(obs)`. Compare to `clouddrift.datasets.gd1h()`

**Comment by kevinsantana11** [comment]
@selipot it looks like we may need to modify the ragged array data structure to achieve this and would need to update some of our example jupyter notebooks (e.g. - https://github.com/Cloud-Drift/gdp-get-started/blob/main/get_started_with_hourly_gdp_data.ipynb). 

Currently each data array `sst, lat, lon, ve, vn, etc...` in the dataset is stored as a contiguous array where we use the coordinates to identify each data points associated drifter_id(id, coord)  and time stamp (time, coord), both of length `obs`. If we wanted the `id` coordinate variable to be associated with the `traj` dimension, we could store the start indexes in a metadata variable using the `traj` dimension. We can then derive the end indexes using the `rowsize` variable.

An example like this:
```python
file = 'gdp_v2.00.nc'
url_path = 'https://noaa-oar-hourly-gdp-pds.s3.amazonaws.com/latest/'
ds = xr.open_dataset(url_path+file+'#mode=bytes')

# create the index array
traj_idx = np.insert(np.cumsum(ds.rowsize.values), 0, 0)

n = 2578
# find the index for drifter ID 2578
j = int(np.where(ds.ID==n)[0])
display('drifter index for ID '+str(n)+' is '+str(j))
ds.sst1[slice(traj_idx[j], traj_idx[j+1])]

```


Would instead look like:
```python
file = 'gdp_v2.00.nc'
url_path = 'https://noaa-oar-hourly-gdp-pds.s3.amazonaws.com/latest/'
ds = xr.open_dataset(url_path+file+'#mode=bytes')

start = int(ds.start_idx[ds.ID==2578])
end = start + int(ds.rowsize[ds.ID==2578])

ds.sst1[slice(start, end)]
```

where `start_idx` stores the start of the drifters data segment in the contiguous data arrays `sst, lat, lon, ve, etc..` who have the dimension `obs`.

Alternatively we could also provide a utility index capability similar to xarray/pandas through the RaggedArray data structure that makes this a bit more succinct.

see:
```

ra = raggedarray.from_netcdf("gdp1h_agg_2.02.nc")

ra.sst1[ra.ID==2578]
```

**Comment by selipot** [comment]
I am a bit confused by what you write above. Right now, in order to achieve what we desire, in the `datasets` module we simply do:

```ds = ds.rename_vars({"ID": "id"}).assign_coords({"id": ds.ID}).drop_vars(["ids"])```
