### ISSUE TITLE
adapter for GDP raw files

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#377]
I would like to see written an adapter function for the raw GDP files which can be found on the DAC FTP under `/phod/pub/pazos/data/shane/sst/`

We could actually write three functions, one for each set of raw,p, and s files. The file patterns are
`buoydata_1_5000_rawfiles.dat.gz`
`buoydata_1_5000_edited_pfiles.gz`
`buoydata_1_5000_edited_sfiles.dat.gz`

with the corresponding header descriptions:
`header_buoydata_rawfiles.txt`
`header_buoydata_edited_pfiles.txt`
`header_buoydata_edited_sfiles.txt`

Bonus would be to lift the metadata from the files
`dirfl_1_5000_psfiles.dat`

**Comment by kevinsantana11** [comment]
> I would like to see written an adapter function for the raw GDP files which can be found on the DAC FTP under `/phod/pub/pazos/data/shane/sst/`
> 
> We could actually write three functions, one for each set of raw,p, and s files. The file patterns are `buoydata_1_5000_rawfiles.dat.gz` `buoydata_1_5000_edited_pfiles.gz` `buoydata_1_5000_edited_sfiles.dat.gz`
> 
> with the corresponding header descriptions: `header_buoydata_rawfiles.txt` `header_buoydata_edited_pfiles.txt` `header_buoydata_edited_sfiles.txt`
> 
> Bonus would be to lift the metadata from the files `dirfl_1_5000_psfiles.dat`

Hi Shane (@selipot), couple of questions:

* Do the headers: `Sensor4,Sensor5,Sensor6,Quality Index` have any units? Mainly look for context on these
* does the metadata apply across the raw, p and s data files?
* do we know if the metadata file follows the same format as the one used for the [6h dataset](https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/) ?

**Comment by selipot** [comment]
- SensorX are placeholders for extra sensors so no known unit a priori
- Metadata apply to all three types of files
- I have lost track of the metadata file formats. That could be a question for @RickLumpkin or Shaun Dolk

Note that the p (position) files and s (sensor) files are extracted from the raw files
