### ISSUE TITLE
Rename `ragged_array` -> `RaggedArray`

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#38]
The Python style guide recommends TitleCase for [class names](https://peps.python.org/pep-0008/#class-names).

This is a very minor issue. Newcomers to the library who are familiar with Python may be on first look get the idea that 

```python
from clouddrift import ragged_array
```

is a function and not a class. Since the project is very young and there are a few if any users, I think it'd be good to address this now and be consistent with the Python style guide for the public API.

**Comment by selipot** [comment]
I agree that we should follow an established style guide. I trust you to address/change these things as you think is best.
