### ISSUE TITLE
What dependencies are needed?

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#41]
In pyproject.toml we have

```
dependencies = [
    "numpy>=1.22.4",
    "pandas>=1.4.2",
    "xarray>=2022.3.0",
    "netcdf4>=1.5.8",
    "pyarrow>=8.0.0",
    "zarr>=2.11.3",
    "numba>=0.53.1",
    "tqdm>=4.64.0",
    "fsspec>=2022.3.0",
    "awkward==1.9.0",
]
```

From my scanning of the project, we're not using ~~fsspec~~, pandas, zarr, and numba. Can they be safely removed? We're not using netCDF4 directly, but it's an optional dependency of xarray.

**Comment by milancurcic** [comment]
fsspec is an optional dependency of `ak.to_parquet()` and needs to be included. Otherwise, the project builds and passes tests without numba, pandas, and zarr. I think they should be removed. Notebooks that need them should sit in a different repo. What do you think?

**Comment by selipot** [comment]
Before doing this, let's discuss at our next meeting where the notebooks for the pedagogical component of the project should live. I think I agree with you that they can be in another repo under the github `Cloud-Drift` project just like we have the earthcube meeting repo or the `gdp-get-started` repo.
