### ISSUE TITLE
pip vs conda install in README.md

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#56]
@philippemiron @milancurcic :
- pip vs conda install on the README.md ?
- if the conda install persist, change the name of the environment from clouddrift to clouddrift_env or something?
- do we really need the conda environment install? for development?

**Comment by milancurcic** [comment]
To clarify Shane's question, we were wondering if the instructions for creating the Conda environment were necessary and if yes, what's their purpose? I thought that we could just do `pip install clouddrift` from a Conda environment.

**Comment by selipot** [comment]
I guess `pip install` is for the installing the latest release but the conda install of the repo is for installing the latest developments? Maybe it is not clear in the README. Also, what is the obstacle again to have a conda install as in `conda install clouddrift`?
