### ISSUE TITLE
Function to compute velocity from positions

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#62]
Let's discuss the API for this function.

```python
def velocity_from_positions(
    x: xr.DataArray,
    y: xr.DataArray,
    time: xr.DataArray,
    coords: str='spherical', # where x is lon and y is lat, otherwise can be 'cartesian' where x is eating and y is northing
    order: int=1, # can also be 2 for centered difference; we can discuss if higher orders may be desired
) -> Tuple(xr.DataArray, xr.DataArray)
```

I wonder if we shouldn't use `coords` to avoid confusion with the Xarray special `coords`. Perhaps `coord_system` or `coordinate_system`?

Until there is native support for ragged arrays in Xarray, the user should be careful to not run this on multiple consecutive trajectories. It will be easy for this function to detect that (e.g. jump in time and space) and issue a warning.

**Comment by selipot** [comment]
sure, `coord_system` could work. in addition or instead of order we could have schemes? (forward, backward, centered)

**Comment by milancurcic** [comment]
I assume what you mean by forward and backward is the same as upstream and downstream in space in the context of advection. I considered this initially but realized it's redundant. Here's why:

Upstream vs downstream is the same calculation for `dx`: `x[1:]` - `x[:-1]`. The only difference is where `dx` is evaluated--at x[:-1] (upstream/backward) or x[1:] (downstream/forward). But if the function returns only the velocity and not the position of that velocity, it's up to the user to decide.

And if the user doesn't need to do anything about advection, then it doesn't matter--the position of the resultant velocity is at centerpoints `(x[1:] + x[:-1]) / 2`. 

Is that what you meant or am I writing about something different?

**Comment by selipot** [comment]
For now, let's follow `latlon2uv.m` in jLab. Have a look.

**Comment by milancurcic** [comment]
[latlon2uv](http://jmlilly.net/doc/latlon2uv.html)

>     Difference algorithm
>  
>     By default, LATLON2UV uses a first central difference algorithm which 
>     is defined to be the average of a forward and a backward difference.
>  
>     CV=LATLON2UV(...,'forward') instead uses a first forward difference. 
>     Velocity is computed based on the great circle distance and bearing 
>     from each point to the next point.  
>  
>     CV=LATLON2UV(...,'backward') instead uses a first backward difference.  
>     Velocity is computed based on the great circle distance and bearing 
>     from each point to the previous point.  This is equivalent to the first 
>     forward difference computed backward in time.
>  
>     The first forward and first backward difference can be thought of as 
>     giving the Cartesian velocities of a departing and arriving particle,
>     respectively.
>  
>     Note that acceleration is not output when the 'forward' or 'backward'
>     algorithms are specified, as acceleration is computed as a part of the 
>     first central difference operation.

Let's discuss this more.

In the case of a 1st order difference, do you think the size of `dx` should be the same as the size of `x`, or less by 1?

**Comment by selipot** [comment]
`dx` definitively should be the same size as `x`. See how the end points are handled in `latlon2uv.m` on line 261-263.

**Comment by milancurcic** [comment]
OK, in my mind I'd think the opposite, but at the same time, I don't know of an established convention either way. We can certainly make the result the same size as the inputs, and patch the endpoints, but we should clearly document what we do there, since it may not be expected by everybody.

**Comment by jonathanlilly** [comment]
I just want to echo Shane's preference that length does not change when we compute velocity.  Although it might be mathematically weird, it makes a big headache if length changes when we take the finite difference. 

So the way I handle this in latlon2uv is to take the first forward difference, and first backward difference (both of which are well defined on the sphere) and average them.  Then at the first point and last point I use only the first forward and first backward difference, respectively, so those points are treated specially. 

Probably it could be done a little more nicely by taking the time to write down the first central difference on the sphere. Unlike the Cartesian case, I don't think the average of the forward and backward difference will end up being identical to the central difference. 

You've no doubt thought of this, but it's worth mentioning that we don't want to work with irregularly spaced data in time, so it should be built in that time must progress uniformly.

**Comment by milancurcic** [comment]
> I just want to echo Shane's preference that length does not change when we compute velocity. Although it might be mathematically weird, it makes a big headache if length changes when we take the finite difference.

I'm not surprised at all. :) I don't think it's even mathematically weird, but more from what I'm used to with numerical Python APIs. Specifically, `np.diff()` by default returns one point less, so it turns out that that's what I'm used to expect. But it can certainly be nice for many users for end-points to be taken care of by the library. I already took that approach in #64.

> You've no doubt thought of this, but it's worth mentioning that we don't want to work with irregularly spaced data in time, so it should be built in that time must progress uniformly.

As I understand it, it's only problematic for centered differencing. For forward and backward, the user gets exactly what they ask for, even for irregular dt. But the interpretation must be careful then. If anything, I'd raise a user warning in case of irregular dt, but not error out. Would you error out?

**Comment by selipot** [comment]
I think the function returns the velocity in meter per unit of time input, correct? If yes we need to update the help. Can the function be made aware of the unit of the time and automatically return the velocity in m/s? with an option for that behavior to be disabled?

**Comment by milancurcic** [comment]
I opened #72 to discuss this further. Let's open new issues whenever new problems and questions arise, so they're easier to find. I'll close this one.
