### ISSUE TITLE
failed install of clouddrift on HPC triton at UM

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#66]
Installing the developper version of clouddrift fails even after loading a module to have a recent version of cmake. Error is below. Note it says clouddrift built successfully but it is not available in my environment
``
...
copying pyarrow/tests/data/parquet/v0.7.1.some-named-index.parquet -> build/lib.linux-ppc64le-cpython-310/pyarrow/tests/data/parquet
      running build_ext
      creating /tmp/pip-install-dc72ev4z/pyarrow_d29963b5e592436b82282ff9a8c4a3d3/build/cpp
      -- Running CMake for PyArrow C++
      cmake -DARROW_BUILD_DIR=build -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-dc72ev4z/pyarrow_d29963b5e592436b82282ff9a8c4a3d3/build/dist -DPYTHON_EXECUTABLE=/home/selipot/miniconda3/envs/research/bin/python3.10 -DPython3_EXECUTABLE=/home/selipot/miniconda3/envs/research/bin/python3.10 -DPYARROW_CXXFLAGS= -DPYARROW_WITH_DATASET=off -DPYARROW_WITH_PARQUET_ENCRYPTION=off -DPYARROW_WITH_HDFS=off -DPYARROW_WITH_FLIGHT=off /tmp/pip-install-dc72ev4z/pyarrow_d29963b5e592436b82282ff9a8c4a3d3/pyarrow/src
      -- The C compiler identification is GNU 8.3.1
      -- The CXX compiler identification is GNU 8.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:63 (find_package):
        By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Arrow", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "Arrow" with any of
        the following names:
      
          ArrowConfig.cmake
          arrow-config.cmake
      
        Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
        "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-dc72ev4z/pyarrow_d29963b5e592436b82282ff9a8c4a3d3/build/cpp/CMakeFiles/CMakeOutput.log".
      error: command '/share/builds/ppcle/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/cmake-3.20.2-ghhqkkvhbflxpgxyzumbfrip46j4ga3f/bin/cmake' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
Successfully built clouddrift
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects
``

**Comment by milancurcic** [comment]
Here's what I found works for me. This is with conda 22.11.1:

```
conda create -n clouddrift
conda install netCDF4 pyarrow
pip install clouddrift
```

In summary, first install netCDF4 and pyarrow dependencies using conda, then install clouddrift using pip.

As I understand it, the extra step is needed because netCDF4 and pyarrow don't have pre-built distributions for ppc64 in PyPI, but they do in the conda repo. The rest is installable via pip.
