### ISSUE TITLE
`velocity_from_position`: Handle n-d arrays

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#69]
Previous discussion in #68.

This issue is to discuss whether and how should `velocity_from_position` handle n-d arrays. Some specific questions:

* Is 2-d sufficient for most use cases or is n-d also useful? The second obvious dimension here are trajectories.
* If not, what are the use cases for n-d?

**Comment by selipot** [comment]
One can imagine any other dimension such as ensemble, depth, etc. To me it seems that 2d is just a special case of n-d.

**Comment by milancurcic** [comment]
I think the function can be modified in a few small ways to accept n-d arrays.

**Comment by selipot** [comment]
Overall we should follow the philosophy of the relevant functions in jLab that accept 2-d arrays (but by expecting time to be in the column direction) as well as cell arrays which is the data structure used to handle Lagrangian data.

**Comment by selipot** [comment]
see https://github.com/Cloud-Drift/clouddrift/issues/68#issuecomment-1381062954
