### ISSUE TITLE
Allow specifying the time axis for multi-dimensional input arrays to `velocity_from_position`

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#73]
In https://github.com/Cloud-Drift/clouddrift/pull/71#issuecomment-1381932552 @selipot wrote:

> For this and future functions that are dimension-aware, could we make it more flexible for the user by passing arguments as needed time_axis = n_1?

**Comment by milancurcic** [comment]
We could, but I don't think it's a good idea. Differencing along a slow-varying axis would hurt performance. And again, I should mention the added cost for us to develop and maintain all the possible cases for something that's likely an edge case. We have an opportunity to teach the user how best to work with Lagrangian data. If time is not the fastest-varying dimension, reshape the data, please! :) (my opinion here is in the same spirit as with the units management in #72).

A potential good use case for this could be if there is a dimension in Lagrangian datasets that varies faster than time. Is there such a dimension in your experience?

**Comment by selipot** [comment]
I am not sure why we would want to teach users about fast-axis. I myself know barely what this means. As a Matlab user I tend to put time in the column direction (and that's the expectation for many jLab functions). So I still think that allowing time to be along any axis would be nice for the users.

Would it make sense not to differentiate along a slow axis but swap axes to put time last? Then swap back the axes to the order of the input?  

As for a dimension faster than time for Lagrangian ... what about depth for Argo floats and gliders?

**Comment by milancurcic** [comment]
Sorry, I didn't mean that we should teach the user about memory layout. I meant it as, I think that we should provide one recommended way of doing things, rather than giving the possibility to do anything. In other words, our library should establish a convention for users to follow, rather than trying to support all possible user conventions. It would certainly be nice for the user if they could choose an axis. I think it's a matter of style that we choose to have for a library, not a right or wrong kind of thing.

> Would it make sense not to differentiate along a slow axis but swap axes to put time last? Then swap back the axes to the order of the input?

Yes, we could do that. It's an implementation detail. It's possible that it may be simpler to differentiate along the slower-varying axis, because we use `np.diff` for 1st order differences, an `np.diff` supports specifying an axis.

> As for a dimension faster than time for Lagrangian ... what about depth for Argo floats and gliders?

Cool, exactly what I was looking for, I'm not familiar with these datasets. Is the typical memory layout for these data then `(traj, obs, depth)`? That's a good use case to allow choosing an axis to differentiate along.

**Comment by milancurcic** [comment]
> Is the typical memory layout for these data then (traj, obs, depth)? That's a good use case to allow choosing an axis to differentiate along.

On second thought, this is probably not a use case. Do Argo floats really have a different position (and thus velocity) for each depth level? I thought the position is only a surface value because of GPS limitations. So even if the data is of shape `(traj, obs, depth)`, the longitude and latitude are only `(traj, obs)`, no?

So perhaps our only use-case for now is when the data is of the `(obs, traj)` shape.
