### ISSUE TITLE
Download file again if present but the remote GDP file is newer

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#95]
See https://github.com/Cloud-Drift/clouddrift/pull/88#discussion_r1089777277

**Comment by philippemiron** [comment]
Is this completed with one of your latest pr @kevinsantana11 ?

**Comment by kevinsantana11** [comment]
@philippemiron yes this should be completed with the latest PR. I have a test verifying the functionality as well: https://github.com/Cloud-Drift/clouddrift/blob/main/tests/adapters/utils_tests.py#L35. Closing
