### ISSUE TITLE
Implement `from_gdp1h` from AWS

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#96]
```python
def from_gdp1h() -> xr.Dataset:
    ...
```

This can go in `clouddrift/adapters/__init__.py` unless a better idea comes up.

**Comment by philippemiron** [comment]
I don't really understand the goal of this function. If it's to subsampled than you can do directly:

```
from clouddrift import subset
ds = xr.open_dataset(...)
ds = subset(ds, {"ID": [1, 2, 3]})
```
and again, this only makes sense if you are running something on AWS. Otherwise, it will be extremely slow.

**Comment by milancurcic** [comment]
I think the only benefit is to hide the URL variable from the user, so they don't have to fiddle with it. Indeed, it's a minimal convenience wrapper. It's possible that it's better to not include it.

**Comment by milancurcic** [comment]
I just thought of another argument. For other custom datasets like GLAD or LASER whose canonical source is not a NetCDF, there may be convenience functions `from_glad` or `from_laser` that implement the preprocessing flow from cloudrun-examples. If so, then it would be more clear to simply provide a minimal `from_gdp[16]h` wrapper, rather than to make a caveat in the docs that if the user wants to work with GDP, they should just use `xr.open_dataset` directly.

**Comment by milancurcic** [comment]
Done by #188
